# Data Analysis Process
1. Asking Questions
2. Data Wrangling
    - Gathering Data
        + csv files
        + APIs
        + Web Scraping
        + Databases
    - Assessing Data
    - Cleaning Data
3. Exploratory Data Analysis
4. Drawing Conclusion
5. Communicating Results

### 1b. Data Accessing
In this step, the data is to be understand more deeply, Before implementing methods to clean it, you will definitely need to have a better idea about what the data is about.

### Types of Unclean Data
###### There are 2 kinds of unclean Data
1. Dirty Data (Data with Quality Issues): low quality data has content issues.
    - Duplicated Data
    - Missing Data
    - Corrupt Data
    - Inaccurate Data
2. Messy Data (Data with tidiness issues): Data has structural issues.
    - Each variable forms a column
    - Each observation forms a row
    - Each observational unit forms a table

Data Cleaning and accessing framework

In [1]:
import pandas as pd
import numpy as np

In [5]:
patients = pd.read_csv(r'data/patients.csv')
treatments = pd.read_csv(r'data/treatments.csv')
adverse_reactions = pd.read_csv(r'data/adverse_reactions.csv')
treatments_cut = pd.read_csv(r'data/treatments_cut.csv')

In [6]:
# View Datasets
patients.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

In [7]:
treatments.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.97
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32

In [9]:
treatments_cut.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,jožka,resanovič,22u - 30u,-,7.56,7.22,0.34
1,inunnguaq,heilmann,57u - 67u,-,7.85,7.45,NaN
2,alwin,svensson,36u - 39u,-,7.78,7.34,NaN
3,thể,lương,-,61u - 64u,7.64,7.22,0.92
4,amanda,ribeiro,36u - 44u,-,7.85,7.47,0.38

In [10]:
adverse_reactions.head()

  given_name     surname           adverse_reaction
0      berta  napolitani  injection site discomfort
1       lena        baer               hypoglycemia
2     joseph         day               hypoglycemia
3     flavia  fiorentino                      cough
4    manouck     wubbels          throat irritation

## 1. Write a Summary for your Data
##### This is a dataset about 500 patients of which 350 patients participated in a clinical trail. None of the patients were using Novodra(a popular injectable insulin) or Auralin (the oral insulin being researched) as their primary source of the insulin before. All wes=re experiencing elevated HbA1c levels.

##### All 350 patients were treated with Novodra to establish a baseline HbA1c level and insulin dose. After 4 weeks, which isnt enough time to capture all the changes in HbA1c that can be arrtibuted by the switch to Auralin or Novodra
    - 175 patients switched to Auralin for 24 weeks
    - 175 patients continued using Novodra for 24 weeks
##### Data about patients feeling some adverse effects is also recorded

## 2. Writing Column Descriptions
#### Table  -> TableName1:
    - col1: Desc
    - col2: Desc
    - col3: Desc
    - col4: Desc

## 2. Writing Column Descriptions
#### Table  -> TableName2:
    - col1: Desc
    - col2: Desc
    - col3: Desc
    - col4: Desc

### 3. Add any additional information

### 4. Types of Assessments
##### There are 2 types of assessments styles
    - Manual - Looking through the data manually in google sheets
    - Programmatic - By using pandas functions such as info(), describe(), or sample()

### Steps in Assessments
##### There are 2 types of assessments
    - Discover
    - Document

In [12]:
# export data for manual assessment

with pd.ExcelWriter('data/clinical_trails.xlsx') as writer:
    patients.to_excel(writer, sheet_name='patients', index=False)
    treatments.to_excel(writer, sheet_name='treatments', index=False)
    adverse_reactions.to_excel(writer, sheet_name='adverse_reactions', index=False)
    treatments_cut.to_excel(writer, sheet_name='treatments_cut', index=False)

### Issues with the Dataset

1. Data Dirty

    Table - `Patient`
    - patient_id = 9 has misspelled name'dsvid' instead of 'David'  `Accuacy`
    - state column somethimes contains full name & sometimes contains abbiviations  `Consistency`
    - zip code columns has entries with 4 digits    `Validity`
    - Data missing for 12 patients in address, city, state,	zip_code, country, contact  `Completeness`
    - Incorrect data type assigned to assigned_sex, zip_code and birthdate  `Validity`
    - duplicate entries by the name of the John Doe     `Accuracy`
    - One patient has weight = 48.800000 pounds     `Accuracy`
    - Once patient has height = 27.000000 inches    `Accuacy`

    Table - `Treatments` & `Treatments_cuts`
    - given name and surname col is all in lower case   `Consistency`
    - remove u from Auralin and Navodra columns     'Validity'
    - - in Novodra and AUralin col treated as NaN   `Validity`
    - missing values in hb1Ac_change       `Completeness`
    - one duplicate entry by the name joseph day    `Accuracy`
    - in hbA1c 9 instead of 4 or need to calc differnet in another columns  `Accuracy`

    Table - `Adverse_Reactions`
    - given name and surname col is all in lower case   `Consistency`
2. Messy Data

    Table - 'Patient'
    - contact col contains both phone and email

    Table - `Treatments` & `Treatments_cuts`
    - Auralin and Navodra col should be spilt into 2 cols start and end dose
    - Merge both the tables

    Table - `Adverse_reaction`
    - this table should not exist independently.

### Automatic Assessment
1. Head and Tail
2. Sample
3. Info
4. isnull
5. Duplicated
6. describe

In [14]:
patients.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

In [15]:
patients.sample(5)

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
265,266,female,Þórunn,Tryggvadóttir,77 Juniper Drive,Mio,MI,48647.0,United States,orunnTryggvadottir@dayrep.com+1 (989) 826-7884,6/9/1978,120.0,69,17.7
93,94,male,Elliot,Richardson,4230 Ridenour Street,Sunrise,FL,33323.0,United States,786-234-0038ElliotRichardson@teleworm.us,1/14/1973,168.1,71,23.4
472,473,female,Julia,Werner,325 Eastland Avenue,Natchez,MS,39120.0,United States,601-446-6829JuliaWerner@teleworm.us,9/14/1938,155.3,61,29.3
269,270,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,NaN,10/9/1937,175.2,61,33.1
9,10,female,Sophie,Cabrera,3303 Anmoore Road,New York,New York,10011.0,United States,SophieCabreraIbarra@teleworm.us1 718 795 9124,12/3/1930,194.7,64,33.4

In [16]:
patients.info()

<class 'pandas.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    str
 2   given_name    503 non-null    str
 3   surname       503 non-null    str
 4   address       491 non-null    str
 5   city          491 non-null    str
 6   state         491 non-null    str
 7   zip_code      491 non-null    float64
 8   country       491 non-null    str
 9   contact       491 non-null    str
 10  birthdate     503 non-null    str
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
dtypes: float64(3), int64(2), str(9)
memory usage: 55.1 KB

In [19]:
patients[patients['address'].isnull()]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
209,210,female,Lalita,Eldarkhanov,NaN,NaN,NaN,NaN,NaN,NaN,8/14/1950,143.4,62,26.2
219,220,male,Mỹ,Quynh,NaN,NaN,NaN,NaN,NaN,NaN,4/9/1978,237.8,69,35.1
230,231,female,Elisabeth,Knudsen,NaN,NaN,NaN,NaN,NaN,NaN,9/23/1976,165.9,63,29.4
234,235,female,Martina,Tománková,NaN,NaN,NaN,NaN,NaN,NaN,4/7/1936,199.5,65,33.2
242,243,male,John,O'Brian,NaN,NaN,NaN,NaN,NaN,NaN,2/25/1957,205.3,74,26.4
249,250,male,Benjamin,Mehler,NaN,NaN,NaN,NaN,NaN,NaN,10/30/1951,146.5,69,21.6
257,258,male,Jin,Kung,NaN,NaN,NaN,NaN,NaN,NaN,5/17/1995,231.7,69,34.2
264,265,female,Wafiyyah,Asfour,NaN,NaN,NaN,NaN,NaN,NaN,11/3/1989,158.6,63,28.1
269,270,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,NaN,10/9/1937,175.2,61,33.1
278,279,female,Generosa,Cabán,NaN,NaN,NaN,NaN,NaN,NaN,12/16/1962,124.3,69,18.4
286,287,male,Lewis,Webb,NaN,NaN,NaN,NaN,NaN,NaN,4/1/1979,155.3,68,23.6
296,297,female,Chỉ,Lâm,NaN,NaN,NaN,NaN,NaN,NaN,5/14/1990,181.1,63,32.1

In [20]:
patients.duplicated().sum()

np.int64(0)

In [21]:
patients['patient_id'].duplicated().sum()

np.int64(0)

In [23]:
patients.duplicated(subset=['given_name', 'surname']).sum()

np.int64(5)

In [26]:
patients[patients.duplicated(subset=['given_name', 'surname'])]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
229,230,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
237,238,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
244,245,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
251,252,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
277,278,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4

In [29]:
treatments[treatments.duplicated()]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
136,joseph,day,29u - 36u,-,7.7,7.19,NaN

In [31]:
treatments[treatments.duplicated(subset=['given_name', 'surname'])]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
136,joseph,day,29u - 36u,-,7.7,7.19,NaN

In [32]:
treatments_cut[treatments.duplicated()]

C:\Users\Preet Kumar\AppData\Local\Temp\ipykernel_17728\2690857920.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  treatments_cut[treatments.duplicated()]

Empty DataFrame
Columns: [given_name, surname, auralin, novodra, hba1c_start, hba1c_end, hba1c_change]
Index: []

In [34]:
treatments_cut[treatments.duplicated(subset=['given_name', 'surname'])]

C:\Users\Preet Kumar\AppData\Local\Temp\ipykernel_17728\2244419304.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  treatments_cut[treatments.duplicated(subset=['given_name', 'surname'])]

Empty DataFrame
Columns: [given_name, surname, auralin, novodra, hba1c_start, hba1c_end, hba1c_change]
Index: []

In [35]:
adverse_reactions.duplicated().sum()

np.int64(0)

In [36]:
patients.describe()

       patient_id      zip_code      weight      height         bmi
count  503.000000    491.000000  503.000000  503.000000  503.000000
mean   252.000000  49084.118126  173.434990   66.634195   27.483897
std    145.347859  30265.807442   33.916741    4.411297    5.276438
min      1.000000   1002.000000   48.800000   27.000000   17.100000
25%    126.500000  21920.500000  149.300000   63.000000   23.300000
50%    252.000000  48057.000000  175.300000   67.000000   27.200000
75%    377.500000  75679.000000  199.500000   70.000000   31.750000
max    503.000000  99701.000000  255.900000   79.000000   37.700000

In [38]:
patients[patients['weight'] == 48.800000]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
210,211,female,Camilla,Zaitseva,4689 Briarhill Lane,Wooster,OH,44691.0,United States,330-202-2145CamillaZaitseva@superrito.com,11/26/1938,48.8,63,19.1

In [40]:
patients[patients['height'] == 27.000000]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

In [41]:
treatments.describe()

       hba1c_start   hba1c_end  hba1c_change
count   280.000000  280.000000    171.000000
mean      7.985929    7.589286      0.546023
std       0.568638    0.569672      0.279555
min       7.500000    7.010000      0.200000
25%       7.660000    7.270000      0.340000
50%       7.800000    7.420000      0.380000
75%       7.970000    7.570000      0.920000
max       9.950000    9.580000      0.990000

In [43]:
treatments[treatments['hba1c_start'] == 9.950000]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
166,annie,allen,36u - 42u,-,9.95,9.58,0.37

In [46]:
treatments.sort_values(by='hba1c_start', ascending=False)

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
166,annie,allen,36u - 42u,-,9.95,9.58,0.37
75,mackenzie,mckay,-,44u - 43u,9.87,9.48,0.39
81,robert,wagner,43u - 49u,-,9.84,9.52,0.32
171,justyna,kowalczyk,24u - 34u,-,9.84,9.44,NaN
25,benoît,bonami,-,44u - 43u,9.82,9.40,0.92
...,...,...,...,...,...,...,...
105,finlay,sheppard,-,31u - 30u,7.51,7.17,0.34
53,nasser,mansour,-,33u - 31u,7.51,7.06,0.95
126,jowita,wiśniewska,-,22u - 23u,7.50,7.08,0.92
270,mika,martinsson,34u - 43u,-,7.50,7.17,0.33
113,kari,laatikainen,39u - 43u,-,7.50,7.11,NaN

### `Note:` Accesing data is iterative process

### Data Quality Dimensions (For Dirty Data)
    - Completenss -> Is data missing?
    - Validate -> is data invalid -> negative height -> duplicate patient id
    - Accuacy -> data is valid but not accurate -> weight -> 1kg
    - Consistency -> both valid and accurate but differnet writthen -> New Yok and NY

### Order of Severity

Completeness <- Validity <- Accuracy <- Consistency

### Data Cleaning Order
1. Quality -> Completeness
2. Tidiness (Messy Data)
3. Quality -> Validity
4. Quality -> Accuracy
5. Quality -> Consistency

### Steps involved in Cleaning
    - Define
    - Code
    - Test

    `Always make sure to create a copy of your pandas dataframe before you start the cleaning process`

In [55]:
# Creating copies of each df
patients_df = patients.copy()
treatments_df = treatments.copy()
treatments_cut_df = treatments_cut.copy()
adverse_reactions_df = adverse_reactions.copy()

### Define

- replace all missing values of patients df with no data
- subtract hbA1c_start from hbA1c_end to get all changed values
- In patients table Regex to seperate emails and phone number

- Merge both the tables

In [51]:
#  - Data missing for 12 patients in address, city, state,	zip_code, country, contact  `Completeness`

patients[patients_df['address'].isnull()]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
209,210,female,Lalita,Eldarkhanov,NaN,NaN,NaN,NaN,NaN,NaN,8/14/1950,143.4,62,26.2
219,220,male,Mỹ,Quynh,NaN,NaN,NaN,NaN,NaN,NaN,4/9/1978,237.8,69,35.1
230,231,female,Elisabeth,Knudsen,NaN,NaN,NaN,NaN,NaN,NaN,9/23/1976,165.9,63,29.4
234,235,female,Martina,Tománková,NaN,NaN,NaN,NaN,NaN,NaN,4/7/1936,199.5,65,33.2
242,243,male,John,O'Brian,NaN,NaN,NaN,NaN,NaN,NaN,2/25/1957,205.3,74,26.4
249,250,male,Benjamin,Mehler,NaN,NaN,NaN,NaN,NaN,NaN,10/30/1951,146.5,69,21.6
257,258,male,Jin,Kung,NaN,NaN,NaN,NaN,NaN,NaN,5/17/1995,231.7,69,34.2
264,265,female,Wafiyyah,Asfour,NaN,NaN,NaN,NaN,NaN,NaN,11/3/1989,158.6,63,28.1
269,270,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,NaN,10/9/1937,175.2,61,33.1
278,279,female,Generosa,Cabán,NaN,NaN,NaN,NaN,NaN,NaN,12/16/1962,124.3,69,18.4
286,287,male,Lewis,Webb,NaN,NaN,NaN,NaN,NaN,NaN,4/1/1979,155.3,68,23.6
296,297,female,Chỉ,Lâm,NaN,NaN,NaN,NaN,NaN,NaN,5/14/1990,181.1,63,32.1

In [63]:
# code
patients_df['zip_code'] = patients_df['zip_code'].astype(object)

In [64]:
# Code 
patients_df.fillna('No data', inplace=True)

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,499,male,Mustafa,Lindström,2530 Victoria Court,Milton Mills,ME,3852.0,United States,207-477-0579MustafaLindstrom@jourrapide.com,4/10/1959,181.1,72,24.6
499,500,male,Ruman,Bisliev,494 Clarksburg Park Road,Sedona,AZ,86341.0,United States,928-284-4492RumanBisliev@gustr.com,3/26/1948,239.6,70,34.4
500,501,female,Jinke,de Keizer,649 Nutter Street,Overland Park,MO,64110.0,United States,816-223-6007JinkedeKeizer@teleworm.us,1/13/1971,171.2,67,26.8
501,502,female,Chidalu,Onyekaozulu,3652 Boone Crockett Lane,Seattle,WA,98109.0,United States,ChidaluOnyekaozulu@jourrapide.com1 360 443 2060,2/13/1952,176.9,67,27.7
502,503,male,Pat,Gersten,2778 North Avenue,Burr,Nebraska,68324.0,United States,PatrickGersten@rhyta.com402-848-4923,5/3/1954,138.2,71,19.3

In [65]:
# test
patients_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    str
 2   given_name    503 non-null    str
 3   surname       503 non-null    str
 4   address       503 non-null    str
 5   city          503 non-null    str
 6   state         503 non-null    str
 7   zip_code      503 non-null    object
 8   country       503 non-null    str
 9   contact       503 non-null    str
 10  birthdate     503 non-null    str
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
dtypes: float64(2), int64(2), object(1), str(9)
memory usage: 55.1+ KB

In [66]:
# code
treatments_df['hba1c_change'] = treatments_df['hba1c_start'] - treatments_df['hba1c_end']
treatments_cut_df['hba1c_change'] = treatments_cut_df['hba1c_start'] - treatments_cut_df['hba1c_end']

In [67]:
treatments_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    280 non-null    str
 1   surname       280 non-null    str
 2   auralin       280 non-null    str
 3   novodra       280 non-null    str
 4   hba1c_start   280 non-null    float64
 5   hba1c_end     280 non-null    float64
 6   hba1c_change  280 non-null    float64
dtypes: float64(3), str(4)
memory usage: 15.4 KB

In [70]:
treatments_cut_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    70 non-null     str
 1   surname       70 non-null     str
 2   auralin       70 non-null     str
 3   novodra       70 non-null     str
 4   hba1c_start   70 non-null     float64
 5   hba1c_end     70 non-null     float64
 6   hba1c_change  70 non-null     float64
dtypes: float64(3), str(4)
memory usage: 4.0 KB

In [84]:
import re

def find_contact_details(text: str) -> tuple:
    """
    Extracts email and phone numbers cleanly, handling cases where 
    the phone number is directly attached to the front of the email.
    """
    # 1. Patterns
    # This phone pattern grabs the digits, even if letters follow it immediately
    phone_pattern = r'\+?\d[\d -]{6,14}\d'
    email_pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
    
    # 2. Extract Phone First
    phone_match = re.search(phone_pattern, text)
    phone = phone_match.group(0).strip() if phone_match else None
    
    # 3. Extract Email
    email_match = re.search(email_pattern, text)
    email = email_match.group(0) if email_match else None
    
    # 4. Clean-up: If the phone number was accidentally caught inside the email 
    # (e.g., '402-363-6804JaeMDebord@gustr.com'), remove it from the email string.
    if email and phone and email.startswith(phone):
        email = email.replace(phone, "", 1) # Remove only the leading phone number
        
    return (email, phone)

In [89]:
patients_df['email'] = patients_df['contact'].apply(lambda x: find_contact_details(x)).apply(lambda x:x[0])
patients_df['phone'] = patients_df['contact'].apply(lambda x: find_contact_details(x)).apply(lambda x:x[1])

In [93]:
patients_df.drop(columns=['contact'], inplace=True)

In [97]:
# test

patients_df.head(2)

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,email,phone
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,7/10/1976,121.7,66,19.6,ZoeWellish@superrito.com,951-719-9170
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,4/3/1967,118.8,66,19.2,PamelaSHill@cuvox.de,569-3204

In [101]:
# code

treatments_df=pd.concat([treatments_df, treatments_cut_df])

In [102]:
# test

treatments_df

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,0.43
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.47
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,0.43
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32
...,...,...,...,...,...,...,...
65,rovzan,kishiev,32u - 37u,-,7.75,7.41,0.34
66,jakob,jakobsen,-,28u - 26u,7.96,7.51,0.45
67,bernd,schneider,48u - 56u,-,7.74,7.44,0.30
68,berta,napolitani,-,42u - 44u,7.68,7.21,0.47
69,armina,sauvé,36u - 46u,-,7.86,7.40,0.46

In [108]:
# converting two columns into single

treatments_df=treatments_df.melt(id_vars=['given_name', 'surname', 'hba1c_start', 'hba1c_end', 'hba1c_change'], var_name='treatment_type', value_name='treatment_dosage_range')

In [112]:
treatments_df = treatments_df[treatments_df['treatment_dosage_range'] != '-']

In [114]:
treatments_df.head()

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,treatment_type,treatment_dosage_range
0,veronika,jindrová,7.63,7.20,0.43,auralin,41u - 48u
3,skye,gormanston,7.97,7.62,0.35,auralin,33u - 36u
6,sophia,haugen,7.65,7.27,0.38,auralin,37u - 42u
7,eddie,archer,7.89,7.55,0.34,auralin,31u - 38u
9,asia,woźniak,7.76,7.37,0.39,auralin,30u - 36u

In [120]:
treatments_df['treatment_dosage_start']=treatments_df['treatment_dosage_range'].str.split('-').str.get(0)
treatments_df['treatment_dosage_end']=treatments_df['treatment_dosage_range'].str.split('-').str.get(1)

In [122]:
treatments_df.drop(columns=['treatment_dosage_range'], inplace=True)

In [123]:
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,treatment_type,treatment_dosage_start,treatment_dosage_end
0,veronika,jindrová,7.63,7.20,0.43,auralin,41u,48u
3,skye,gormanston,7.97,7.62,0.35,auralin,33u,36u
6,sophia,haugen,7.65,7.27,0.38,auralin,37u,42u
7,eddie,archer,7.89,7.55,0.34,auralin,31u,38u
9,asia,woźniak,7.76,7.37,0.39,auralin,30u,36u
...,...,...,...,...,...,...,...,...
688,christopher,woodward,7.51,7.06,0.45,novodra,55u,51u
690,maret,sultygov,7.67,7.30,0.37,novodra,26u,23u
694,lixue,hsueh,9.21,8.80,0.41,novodra,22u,23u
696,jakob,jakobsen,7.96,7.51,0.45,novodra,28u,26u
698,berta,napolitani,7.68,7.21,0.47,novodra,42u,44u

In [125]:
treatments_df['treatment_dosage_start']=treatments_df['treatment_dosage_start'].str.replace('u','')
treatments_df['treatment_dosage_end']=treatments_df['treatment_dosage_end'].str.replace('u','')

In [129]:
treatments_df['treatment_dosage_start']=treatments_df['treatment_dosage_start'].astype(int)
treatments_df['treatment_dosage_end'] = treatments_df['treatment_dosage_end'].astype(int)

In [130]:
treatments_df.info()

<class 'pandas.DataFrame'>
Index: 350 entries, 0 to 698
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   given_name              350 non-null    str
 1   surname                 350 non-null    str
 2   hba1c_start             350 non-null    float64
 3   hba1c_end               350 non-null    float64
 4   hba1c_change            350 non-null    float64
 5   treatment_type          350 non-null    str
 6   treatment_dosage_start  350 non-null    int64
 7   treatment_dosage_end    350 non-null    int64
dtypes: float64(3), int64(2), str(3)
memory usage: 24.6 KB

In [131]:
treatments_df.head()

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,treatment_type,treatment_dosage_start,treatment_dosage_end
0,veronika,jindrová,7.63,7.20,0.43,auralin,41,48
3,skye,gormanston,7.97,7.62,0.35,auralin,33,36
6,sophia,haugen,7.65,7.27,0.38,auralin,37,42
7,eddie,archer,7.89,7.55,0.34,auralin,31,38
9,asia,woźniak,7.76,7.37,0.39,auralin,30,36

In [133]:
treatments_df = treatments_df.merge(adverse_reactions_df, how='left', on=['given_name', 'surname'])