## What is Data Analytics?
### Process of inspecting, cleansing, transforming, and modeling data with the goal of discovering the useful information.

## **Steps in Data Analysis Process**
1. Asking Questions
    1. What features will contribute to my analysis?
    2. What features are not important for my Analysis
    3. Which of the features have a strong corelation?
    4. Do I need Data Proprocessing?
    5. What kind of feature manipulation/engineering os required?
2. Data Wrangling/Data Munging/ Data Preprocing
#####     process of transforming and mapping data from one 'raw' data form into another format with the intent of making it more appropriate and valuable.
    1. Gathering Data
      1. CSV
      2. API
      3. Web Scraping
      4. Database
    2. Assessing Data
      1. Finding the number of rows and columns(Shape)
      2. Data types of various columns (info())
      3. Checking for missing values (info())
      4. Check for duplicate data(is_unique)
      5. Memory occupied by dataset(info)
      6. High Level mathematical overview of the data(describe)
    3. Cleaning Data
      1. Missing data
      2. Remove Duplicate Data(drop_duplicates)
      3. Incorrect Data types(astype)

3. Exploratory Data Analysis
    1. Finding Patterns
    2. plotting Graphs
    3. Drived co-relations
    4. Drawing Conclusions
    5.  Communicating Results

      1. Exploring Data
        1. Finding corelation and covariance
        2. Doing univarinat and multivarinat analysis
        3. Plotting graphs(Data Visualization)
      2. Augment(Make changes with rep)
          1. Removing outliers
          2. Merging Dataframes
          3. Adding new column
######        These operations are collectively called as feature engineering

4. Drawing Conclusions
  Machine Learning
  Inferential Statistics
  Descriptive Statistics

5. Communicating Results/Data Storytelling
  1. In Person
  2. Blogspot
  3. Reports
  4. PPTs/Slides decks

### **How can I ask better questions?**
1. Subject Matter Expertise (SME)
2. Experience

# **Working with CSV**

# **1. Importing Pandas**

# **2. Opening a Local CSV file**

In [2]:
import pandas as pd

In [5]:
pd.read_csv('data/result.csv')
print(pd)

C:\Users\Preet Kumar\AppData\Local\Temp\ipykernel_18616\2439655387.py:1: DtypeWarning: Columns (0: Address 8, 1: Address 9, 2: Address 10, 3: City, 4: State, 5: State Name, 6: Country) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('data/result.csv')

<module 'pandas' from 'c:\\Users\\Preet Kumar\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\__init__.py'>

## **3. Opening a CSV file from URL**

In [6]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

## **4. Sep Parameter**

In [14]:
# Seperate paramter, by default it is set to ',' you can change it to any format.

pd.read_csv('data/result.csv', sep='\t')

# if there is no header row avaiable in your data set then you can pass an list of columns to the csv file.

# pd.read_csv('data/result.csv', names=['col_1', 'Col_2', 'Col_03'])

       Entity ID,Name,Date of Birth,Place of Birth,Aliases,Titles,Other Information,Direct ID,Effective Date,Entity Level,Expiration Date,Gender,Name Source,Org PID,Original ID,Relationship,Sub Category,Address 1,Address 2,Address 3,Address 4,Address 5,Address 6,Address 7,Address 8,Address 9,Address 10,City,State,State Name,Country,Country Name,Postal Code
0       1123115,"CHENEY, RICHARD BRUCE",1/30/1941,"Lin...
1       1123443,"PARDEW, JAMES WILLIAM JR",2/5/1944,"M...
2       1123445,"BAKER, HOWARD HENRY JR.",11/15/1925,"...
3       1123455,"MILES, RICHARD MONROE",1/8/1937,"Litt...
4       1123456,"MILLER, THOMAS JOEL",12/9/1948,"Chica...
...                                                   ...
210865  19694351,"JANOUSEK, DILLON",,,,"VICE PRESIDENT...
210866  19694352,"WILDER, JARED",2005,,,"SON OF TIFFAN...
210867  19694353,"SPANN, GENEVA",,,,"MOTHER OF TIFFANY...
210868  19694358,"THAMES, CLEO",,,,"MOTHER OF BILLY HO...
210869  19694359,"WILDER, JEFFERY",,"Florence, South C...

[210870 rows x 1 columns]

## **5. Index Col Parameter**

In [15]:
# Replacing default index paramter wiht data set column

pd.read_csv('data/result.csv', index_col='Entity ID')

C:\Users\Preet Kumar\AppData\Local\Temp\ipykernel_18616\3405635157.py:3: DtypeWarning: Columns (0: Address 9, 1: Address 10, 2: City, 3: State, 4: State Name, 5: Country, 6: Country Name) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('data/result.csv', index_col='Entity ID')

,Name,Date of Birth,Place of Birth,Aliases,Titles,Other Information,Direct ID,Effective Date,Entity Level,Expiration Date,...,Address 7,Address 8,Address 9,Address 10,City,State,State Name,Country,Country Name,Postal Code
Entity ID,,,,,,,,,,,,,,,,,,,,,
1123115,"CHENEY, RICHARD BRUCE",1/30/1941,"Lincoln, Nebraska, United States","CHENEY, DICK",FORMER VICE PRESIDENT OF THE UNITED STATES (JA...,Career: Vice President of the United States (J...,https://accuity.worldcompliance.com/signin.asp...,1974.0,National,1975.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1123443,"PARDEW, JAMES WILLIAM JR",2/5/1944,"Memphis, Tennessee, United States","PARDUE, JAMES",FORMER AMBASSADOR OF THE UNITED STATES TO BULG...,NickName: Jimmy; Career: Ambassador of the Uni...,https://accuity.worldcompliance.com/signin.asp...,2002.0,International,2005.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1123445,"BAKER, HOWARD HENRY JR.",11/15/1925,"Huntsville, Tennessee, United States",NaN,FORMER AMBASSADOR OF THE UNITED STATES TO JAPA...,Career: Ambassador of the United States to Jap...,https://accuity.worldcompliance.com/signin.asp...,1977.0,National,1981.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1123455,"MILES, RICHARD MONROE",1/8/1937,"Little Rock, Arkansas, United States",NaN,FORMER INTERIM CHARGE D'AFFAIRES OF THE UNITED...,Career: Interim Charge d'Affaires of the Unite...,https://accuity.worldcompliance.com/signin.asp...,1984.0,International,1987.0,...,"111 AZADLIG AVE, BAKU, AZ, AZERBAIJAN, AZ1007","2201 C ST., NW, US, UNITED STATES, WASHINGTON,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1123456,"MILLER, THOMAS JOEL",12/9/1948,"Chicago, Illinois, United States","MILLER, TOM",FORMER AMBASSADOR OF THE UNITED STATES TO GREE...,Career: Ambassador of the United States to Gre...,https://accuity.worldcompliance.com/signin.asp...,1999.0,International,2001.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19694351,"JANOUSEK, DILLON",NaN,NaN,NaN,VICE PRESIDENT OF PRODUCTION OPERATIONS OF NOR...,Career: Vice President of Production Operation...,https://accuity.worldcompliance.com/signin.asp...,2023.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19694352,"WILDER, JARED",2005,NaN,NaN,"SON OF TIFFANY SPANN-WILDER, MEMBER OF THE SOU...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19694353,"SPANN, GENEVA",NaN,NaN,NaN,"MOTHER OF TIFFANY SPANN-WILDER, MEMBER OF THE ...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19694358,"THAMES, CLEO",NaN,NaN,NaN,"MOTHER OF BILLY HOWARD THAMES, FORMER MEMBER O...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,State,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19694359,"WILDER, JEFFERY",NaN,"Florence, South Carolina, United States",NaN,"HUSBAND OF TIFFANY SPANN-WILDER, MEMBER OF THE...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## **6. Header Parameter**

In [16]:
# When in csv your first row in column but pretend as value
pd.read_csv('data/result.csv', header=0)

C:\Users\Preet Kumar\AppData\Local\Temp\ipykernel_18616\1971084318.py:2: DtypeWarning: Columns (0: Address 8, 1: Address 9, 2: Address 10, 3: City, 4: State, 5: State Name, 6: Country) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('data/result.csv', header=0)

,Entity ID,Name,Date of Birth,Place of Birth,Aliases,Titles,Other Information,Direct ID,Effective Date,Entity Level,...,Address 7,Address 8,Address 9,Address 10,City,State,State Name,Country,Country Name,Postal Code
0,1123115,"CHENEY, RICHARD BRUCE",1/30/1941,"Lincoln, Nebraska, United States","CHENEY, DICK",FORMER VICE PRESIDENT OF THE UNITED STATES (JA...,Career: Vice President of the United States (J...,https://accuity.worldcompliance.com/signin.asp...,1974.0,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1123443,"PARDEW, JAMES WILLIAM JR",2/5/1944,"Memphis, Tennessee, United States","PARDUE, JAMES",FORMER AMBASSADOR OF THE UNITED STATES TO BULG...,NickName: Jimmy; Career: Ambassador of the Uni...,https://accuity.worldcompliance.com/signin.asp...,2002.0,International,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1123445,"BAKER, HOWARD HENRY JR.",11/15/1925,"Huntsville, Tennessee, United States",NaN,FORMER AMBASSADOR OF THE UNITED STATES TO JAPA...,Career: Ambassador of the United States to Jap...,https://accuity.worldcompliance.com/signin.asp...,1977.0,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1123455,"MILES, RICHARD MONROE",1/8/1937,"Little Rock, Arkansas, United States",NaN,FORMER INTERIM CHARGE D'AFFAIRES OF THE UNITED...,Career: Interim Charge d'Affaires of the Unite...,https://accuity.worldcompliance.com/signin.asp...,1984.0,International,...,"111 AZADLIG AVE, BAKU, AZ, AZERBAIJAN, AZ1007","2201 C ST., NW, US, UNITED STATES, WASHINGTON,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1123456,"MILLER, THOMAS JOEL",12/9/1948,"Chicago, Illinois, United States","MILLER, TOM",FORMER AMBASSADOR OF THE UNITED STATES TO GREE...,Career: Ambassador of the United States to Gre...,https://accuity.worldcompliance.com/signin.asp...,1999.0,International,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210865,19694351,"JANOUSEK, DILLON",NaN,NaN,NaN,VICE PRESIDENT OF PRODUCTION OPERATIONS OF NOR...,Career: Vice President of Production Operation...,https://accuity.worldcompliance.com/signin.asp...,2023.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210866,19694352,"WILDER, JARED",2005,NaN,NaN,"SON OF TIFFANY SPANN-WILDER, MEMBER OF THE SOU...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210867,19694353,"SPANN, GENEVA",NaN,NaN,NaN,"MOTHER OF TIFFANY SPANN-WILDER, MEMBER OF THE ...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210868,19694358,"THAMES, CLEO",NaN,NaN,NaN,"MOTHER OF BILLY HOWARD THAMES, FORMER MEMBER O...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,State,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210869,19694359,"WILDER, JEFFERY",NaN,"Florence, South Carolina, United States",NaN,"HUSBAND OF TIFFANY SPANN-WILDER, MEMBER OF THE...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## **7. use_cols Parameters**

In [18]:
pd.read_csv('data/result.csv', usecols=['Name', 'Place of Birth','Entity Level' ])

,Name,Place of Birth,Entity Level
0,"CHENEY, RICHARD BRUCE","Lincoln, Nebraska, United States",National
1,"PARDEW, JAMES WILLIAM JR","Memphis, Tennessee, United States",International
2,"BAKER, HOWARD HENRY JR.","Huntsville, Tennessee, United States",National
3,"MILES, RICHARD MONROE","Little Rock, Arkansas, United States",International
4,"MILLER, THOMAS JOEL","Chicago, Illinois, United States",International
...,...,...,...
210865,"JANOUSEK, DILLON",NaN,NaN
210866,"WILDER, JARED",NaN,National
210867,"SPANN, GENEVA",NaN,National
210868,"THAMES, CLEO",NaN,State
210869,"WILDER, JEFFERY","Florence, South Carolina, United States",National

## **8.Squeeze Parameters**

In [20]:
df = pd.read_csv('data/result.csv')['Entity Level']

# pd.read_csv('result.csv', usecols=['Entity Level'], squeeze=True) # This happens because squeeze was deprecated in pandas 1.4 and removed in pandas 2.0.

C:\Users\Preet Kumar\AppData\Local\Temp\ipykernel_18616\1916559514.py:1: DtypeWarning: Columns (0: Address 8, 1: Address 9, 2: Address 10, 3: City, 4: State, 5: State Name, 6: Country) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/result.csv')['Entity Level']

## **9. Skip rows/nrows Parameter**

In [22]:
pd.read_csv('data/result.csv', skiprows=[1,2,3], on_bad_lines='skip', engine='python') # for skiping rows

,Entity ID,Name,Date of Birth,Place of Birth,Aliases,Titles,Other Information,Direct ID,Effective Date,Entity Level,...,Address 7,Address 8,Address 9,Address 10,City,State,State Name,Country,Country Name,Postal Code
0,1123455,"MILES, RICHARD MONROE",1/8/1937,"Little Rock, Arkansas, United States",NaN,FORMER INTERIM CHARGE D'AFFAIRES OF THE UNITED...,Career: Interim Charge d'Affaires of the Unite...,https://accuity.worldcompliance.com/signin.asp...,1984.0,International,...,"111 AZADLIG AVE, BAKU, AZ, AZERBAIJAN, AZ1007","2201 C ST., NW, US, UNITED STATES, WASHINGTON,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1123456,"MILLER, THOMAS JOEL",12/9/1948,"Chicago, Illinois, United States","MILLER, TOM",FORMER AMBASSADOR OF THE UNITED STATES TO GREE...,Career: Ambassador of the United States to Gre...,https://accuity.worldcompliance.com/signin.asp...,1999.0,International,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1123457,"MONTGOMERY, WILLIAM DALE",1945,NaN,NaN,FORMER AMBASSADOR OF THE UNITED STATES TO SERB...,"Career: January 04, 2002 - February 29, 2004: ...",https://accuity.worldcompliance.com/signin.asp...,1988.0,International,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1123461,"BURNS, ROBERT NICHOLAS",1/28/1956,"Buffalo, New York, United States","BURNS, NICK","AMBASSADOR OF THE UNITED STATES TO CHINA, EFFE...",Career: Ambassador of the United States to Chi...,https://accuity.worldcompliance.com/signin.asp...,2023.0,International,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1123465,"FOGLIETTA, THOMAS MICHAEL",12/3/1928,"Philadelphia, Pennsylvania, United States",NaN,FORMER AMBASSADOR OF THE UNITED STATES IN ROME...,NickName: Tom; Political Party: Democratic. Ca...,https://accuity.worldcompliance.com/signin.asp...,1981.0,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210862,19694351,"JANOUSEK, DILLON",NaN,NaN,NaN,VICE PRESIDENT OF PRODUCTION OPERATIONS OF NOR...,Career: Vice President of Production Operation...,https://accuity.worldcompliance.com/signin.asp...,2023.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210863,19694352,"WILDER, JARED",2005,NaN,NaN,"SON OF TIFFANY SPANN-WILDER, MEMBER OF THE SOU...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210864,19694353,"SPANN, GENEVA",NaN,NaN,NaN,"MOTHER OF TIFFANY SPANN-WILDER, MEMBER OF THE ...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210865,19694358,"THAMES, CLEO",NaN,NaN,NaN,"MOTHER OF BILLY HOWARD THAMES, FORMER MEMBER O...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,State,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210866,19694359,"WILDER, JEFFERY",NaN,"Florence, South Carolina, United States",NaN,"HUSBAND OF TIFFANY SPANN-WILDER, MEMBER OF THE...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# nrows, export n number of rows useful when you are working with large dataset to avoid load millions of rows you can export few of them
pd.read_csv('data/result.csv', nrows=100)

,Entity ID,Name,Date of Birth,Place of Birth,Aliases,Titles,Other Information,Direct ID,Effective Date,Entity Level,...,Address 7,Address 8,Address 9,Address 10,City,State,State Name,Country,Country Name,Postal Code
0,1123115,"CHENEY, RICHARD BRUCE",1/30/1941,"Lincoln, Nebraska, United States","CHENEY, DICK",FORMER VICE PRESIDENT OF THE UNITED STATES (JA...,Career: Vice President of the United States (J...,https://accuity.worldcompliance.com/signin.asp...,1974.0,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1123443,"PARDEW, JAMES WILLIAM JR",2/5/1944,"Memphis, Tennessee, United States","PARDUE, JAMES",FORMER AMBASSADOR OF THE UNITED STATES TO BULG...,NickName: Jimmy; Career: Ambassador of the Uni...,https://accuity.worldcompliance.com/signin.asp...,2002.0,International,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1123445,"BAKER, HOWARD HENRY JR.",11/15/1925,"Huntsville, Tennessee, United States",NaN,FORMER AMBASSADOR OF THE UNITED STATES TO JAPA...,Career: Ambassador of the United States to Jap...,https://accuity.worldcompliance.com/signin.asp...,1977.0,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1123455,"MILES, RICHARD MONROE",1/8/1937,"Little Rock, Arkansas, United States",NaN,FORMER INTERIM CHARGE D'AFFAIRES OF THE UNITED...,Career: Interim Charge d'Affaires of the Unite...,https://accuity.worldcompliance.com/signin.asp...,1984.0,International,...,"111 AZADLIG AVE, BAKU, AZ, AZERBAIJAN, AZ1007","2201 C ST., NW, US, UNITED STATES, WASHINGTON,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1123456,"MILLER, THOMAS JOEL",12/9/1948,"Chicago, Illinois, United States","MILLER, TOM",FORMER AMBASSADOR OF THE UNITED STATES TO GREE...,Career: Ambassador of the United States to Gre...,https://accuity.worldcompliance.com/signin.asp...,1999.0,International,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1124794,"DORGAN, BYRON LESLIE",5/14/1942,"Dickinson, North Dakota, United States",NaN,FORMER TAX COMMISSIONER OF NORTH DAKOTA (MARCH...,Political Party: Democratic Career: Member of ...,https://accuity.worldcompliance.com/signin.asp...,1981.0,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,1124795,"DURBIN, RICHARD JOSEPH",11/21/1944,"East St. Louis, Illinois, United States","DURBIN, DICK",MEMBER OF THE UNITED STATES CONGRESS (JANUARY ...,Political Party: Democratic. Career: Member of...,https://accuity.worldcompliance.com/signin.asp...,1997.0,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,1124796,"EDWARDS, JOHNNY REID",6/10/1953,"Seneca, South Carolina, United States",NaN,FORMER MEMBER OF THE UNITED STATES CONGRESS (J...,NickName: John; Political Party: Democratic. C...,https://accuity.worldcompliance.com/signin.asp...,1999.0,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,1124797,"ENSIGN, JOHN ERIC",3/25/1958,"Roseville, California, United States",NaN,"FORMER MEMBER OF THE SENATE (JANUARY 03, 2001 ...",Political Party: Republican Constituency: Neva...,https://accuity.worldcompliance.com/signin.asp...,1995.0,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,1124798,"ENZI, MICHAEL BRADLEY",2/1/1944,"Bremerton, Washington, United States","ENZI, MIKE",FORMER MEMBER OF THE UNITED STATES CONGRESS (J...,Political Party: Republican Party (GOP). Caree...,https://accuity.worldcompliance.com/signin.asp...,2011.0,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## **10. Encoding Parameter**

In [26]:
pd.read_csv('data/result.csv', encoding='latin-1')

C:\Users\Preet Kumar\AppData\Local\Temp\ipykernel_18616\2470544031.py:1: DtypeWarning: Columns (0: Address 8, 1: Address 9, 2: Address 10, 3: City, 4: State, 5: State Name, 6: Country) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('data/result.csv', encoding='latin-1')

,ï»¿Entity ID,Name,Date of Birth,Place of Birth,Aliases,Titles,Other Information,Direct ID,Effective Date,Entity Level,...,Address 7,Address 8,Address 9,Address 10,City,State,State Name,Country,Country Name,Postal Code
0,1123115,"CHENEY, RICHARD BRUCE",1/30/1941,"Lincoln, Nebraska, United States","CHENEY, DICK",FORMER VICE PRESIDENT OF THE UNITED STATES (JA...,Career: Vice President of the United States (J...,https://accuity.worldcompliance.com/signin.asp...,1974.0,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1123443,"PARDEW, JAMES WILLIAM JR",2/5/1944,"Memphis, Tennessee, United States","PARDUE, JAMES",FORMER AMBASSADOR OF THE UNITED STATES TO BULG...,NickName: Jimmy; Career: Ambassador of the Uni...,https://accuity.worldcompliance.com/signin.asp...,2002.0,International,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1123445,"BAKER, HOWARD HENRY JR.",11/15/1925,"Huntsville, Tennessee, United States",NaN,FORMER AMBASSADOR OF THE UNITED STATES TO JAPA...,Career: Ambassador of the United States to Jap...,https://accuity.worldcompliance.com/signin.asp...,1977.0,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1123455,"MILES, RICHARD MONROE",1/8/1937,"Little Rock, Arkansas, United States",NaN,FORMER INTERIM CHARGE D'AFFAIRES OF THE UNITED...,Career: Interim Charge d'Affaires of the Unite...,https://accuity.worldcompliance.com/signin.asp...,1984.0,International,...,"111 AZADLIG AVE, BAKU, AZ, AZERBAIJAN, AZ1007","2201 C ST., NW, US, UNITED STATES, WASHINGTON,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1123456,"MILLER, THOMAS JOEL",12/9/1948,"Chicago, Illinois, United States","MILLER, TOM",FORMER AMBASSADOR OF THE UNITED STATES TO GREE...,Career: Ambassador of the United States to Gre...,https://accuity.worldcompliance.com/signin.asp...,1999.0,International,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210865,19694351,"JANOUSEK, DILLON",NaN,NaN,NaN,VICE PRESIDENT OF PRODUCTION OPERATIONS OF NOR...,Career: Vice President of Production Operation...,https://accuity.worldcompliance.com/signin.asp...,2023.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210866,19694352,"WILDER, JARED",2005,NaN,NaN,"SON OF TIFFANY SPANN-WILDER, MEMBER OF THE SOU...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210867,19694353,"SPANN, GENEVA",NaN,NaN,NaN,"MOTHER OF TIFFANY SPANN-WILDER, MEMBER OF THE ...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210868,19694358,"THAMES, CLEO",NaN,NaN,NaN,"MOTHER OF BILLY HOWARD THAMES, FORMER MEMBER O...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,State,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210869,19694359,"WILDER, JEFFERY",NaN,"Florence, South Carolina, United States",NaN,"HUSBAND OF TIFFANY SPANN-WILDER, MEMBER OF THE...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## **11. Skip Bad Lines**

In [ ]:
pd.read_csv('data/result.csv', skip_blank_lines=False) # skip blank lines in csv file

# used to read a csv file with a specific encoding, such as 'utf-8' or 'latin-1', to handle special characters in the data.or parser error

C:\Users\Preet Kumar\AppData\Local\Temp\ipykernel_18616\1956448435.py:1: DtypeWarning: Columns (0: Address 8, 1: Address 9, 2: Address 10, 3: City, 4: State, 5: State Name, 6: Country) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('data/result.csv', skip_blank_lines=False) # skip blank lines in csv file

,Entity ID,Name,Date of Birth,Place of Birth,Aliases,Titles,Other Information,Direct ID,Effective Date,Entity Level,...,Address 7,Address 8,Address 9,Address 10,City,State,State Name,Country,Country Name,Postal Code
0,1123115,"CHENEY, RICHARD BRUCE",1/30/1941,"Lincoln, Nebraska, United States","CHENEY, DICK",FORMER VICE PRESIDENT OF THE UNITED STATES (JA...,Career: Vice President of the United States (J...,https://accuity.worldcompliance.com/signin.asp...,1974.0,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1123443,"PARDEW, JAMES WILLIAM JR",2/5/1944,"Memphis, Tennessee, United States","PARDUE, JAMES",FORMER AMBASSADOR OF THE UNITED STATES TO BULG...,NickName: Jimmy; Career: Ambassador of the Uni...,https://accuity.worldcompliance.com/signin.asp...,2002.0,International,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1123445,"BAKER, HOWARD HENRY JR.",11/15/1925,"Huntsville, Tennessee, United States",NaN,FORMER AMBASSADOR OF THE UNITED STATES TO JAPA...,Career: Ambassador of the United States to Jap...,https://accuity.worldcompliance.com/signin.asp...,1977.0,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1123455,"MILES, RICHARD MONROE",1/8/1937,"Little Rock, Arkansas, United States",NaN,FORMER INTERIM CHARGE D'AFFAIRES OF THE UNITED...,Career: Interim Charge d'Affaires of the Unite...,https://accuity.worldcompliance.com/signin.asp...,1984.0,International,...,"111 AZADLIG AVE, BAKU, AZ, AZERBAIJAN, AZ1007","2201 C ST., NW, US, UNITED STATES, WASHINGTON,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1123456,"MILLER, THOMAS JOEL",12/9/1948,"Chicago, Illinois, United States","MILLER, TOM",FORMER AMBASSADOR OF THE UNITED STATES TO GREE...,Career: Ambassador of the United States to Gre...,https://accuity.worldcompliance.com/signin.asp...,1999.0,International,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210865,19694351,"JANOUSEK, DILLON",NaN,NaN,NaN,VICE PRESIDENT OF PRODUCTION OPERATIONS OF NOR...,Career: Vice President of Production Operation...,https://accuity.worldcompliance.com/signin.asp...,2023.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210866,19694352,"WILDER, JARED",2005,NaN,NaN,"SON OF TIFFANY SPANN-WILDER, MEMBER OF THE SOU...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210867,19694353,"SPANN, GENEVA",NaN,NaN,NaN,"MOTHER OF TIFFANY SPANN-WILDER, MEMBER OF THE ...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210868,19694358,"THAMES, CLEO",NaN,NaN,NaN,"MOTHER OF BILLY HOWARD THAMES, FORMER MEMBER O...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,State,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210869,19694359,"WILDER, JEFFERY",NaN,"Florence, South Carolina, United States",NaN,"HUSBAND OF TIFFANY SPANN-WILDER, MEMBER OF THE...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## **12. dtypes Parameter**

In [38]:
pd.read_csv('data/result.csv', dtype={'Effective Date': 'Int64'})

C:\Users\Preet Kumar\AppData\Local\Temp\ipykernel_18616\920360173.py:1: DtypeWarning: Columns (0: Address 8, 1: Address 9, 2: Address 10, 3: City, 4: State, 5: State Name, 6: Country) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('data/result.csv', dtype={'Effective Date': 'Int64'})

,Entity ID,Name,Date of Birth,Place of Birth,Aliases,Titles,Other Information,Direct ID,Effective Date,Entity Level,...,Address 7,Address 8,Address 9,Address 10,City,State,State Name,Country,Country Name,Postal Code
0,1123115,"CHENEY, RICHARD BRUCE",1/30/1941,"Lincoln, Nebraska, United States","CHENEY, DICK",FORMER VICE PRESIDENT OF THE UNITED STATES (JA...,Career: Vice President of the United States (J...,https://accuity.worldcompliance.com/signin.asp...,1974,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1123443,"PARDEW, JAMES WILLIAM JR",2/5/1944,"Memphis, Tennessee, United States","PARDUE, JAMES",FORMER AMBASSADOR OF THE UNITED STATES TO BULG...,NickName: Jimmy; Career: Ambassador of the Uni...,https://accuity.worldcompliance.com/signin.asp...,2002,International,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1123445,"BAKER, HOWARD HENRY JR.",11/15/1925,"Huntsville, Tennessee, United States",NaN,FORMER AMBASSADOR OF THE UNITED STATES TO JAPA...,Career: Ambassador of the United States to Jap...,https://accuity.worldcompliance.com/signin.asp...,1977,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1123455,"MILES, RICHARD MONROE",1/8/1937,"Little Rock, Arkansas, United States",NaN,FORMER INTERIM CHARGE D'AFFAIRES OF THE UNITED...,Career: Interim Charge d'Affaires of the Unite...,https://accuity.worldcompliance.com/signin.asp...,1984,International,...,"111 AZADLIG AVE, BAKU, AZ, AZERBAIJAN, AZ1007","2201 C ST., NW, US, UNITED STATES, WASHINGTON,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1123456,"MILLER, THOMAS JOEL",12/9/1948,"Chicago, Illinois, United States","MILLER, TOM",FORMER AMBASSADOR OF THE UNITED STATES TO GREE...,Career: Ambassador of the United States to Gre...,https://accuity.worldcompliance.com/signin.asp...,1999,International,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210865,19694351,"JANOUSEK, DILLON",NaN,NaN,NaN,VICE PRESIDENT OF PRODUCTION OPERATIONS OF NOR...,Career: Vice President of Production Operation...,https://accuity.worldcompliance.com/signin.asp...,2023,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210866,19694352,"WILDER, JARED",2005,NaN,NaN,"SON OF TIFFANY SPANN-WILDER, MEMBER OF THE SOU...",NaN,https://accuity.worldcompliance.com/signin.asp...,<NA>,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210867,19694353,"SPANN, GENEVA",NaN,NaN,NaN,"MOTHER OF TIFFANY SPANN-WILDER, MEMBER OF THE ...",NaN,https://accuity.worldcompliance.com/signin.asp...,<NA>,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210868,19694358,"THAMES, CLEO",NaN,NaN,NaN,"MOTHER OF BILLY HOWARD THAMES, FORMER MEMBER O...",NaN,https://accuity.worldcompliance.com/signin.asp...,<NA>,State,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210869,19694359,"WILDER, JEFFERY",NaN,"Florence, South Carolina, United States",NaN,"HUSBAND OF TIFFANY SPANN-WILDER, MEMBER OF THE...",NaN,https://accuity.worldcompliance.com/signin.asp...,<NA>,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## **13. Handling Dates**

In [44]:
pd.read_csv('data/result.csv', parse_dates=['Date of Birth', 'Place of Birth']).info()

C:\Users\Preet Kumar\AppData\Local\Temp\ipykernel_18616\270704037.py:1: DtypeWarning: Columns (0: Address 8, 1: Address 9, 2: Address 10, 3: City, 4: State, 5: State Name, 6: Country) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('data/result.csv', parse_dates=['Date of Birth', 'Place of Birth']).info()
C:\Users\Preet Kumar\AppData\Local\Temp\ipykernel_18616\270704037.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.read_csv('data/result.csv', parse_dates=['Date of Birth', 'Place of Birth']).info()

<class 'pandas.DataFrame'>
RangeIndex: 210870 entries, 0 to 210869
Data columns (total 33 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Entity ID          210870 non-null  int64
 1   Name               210870 non-null  str
 2   Date of Birth      57807 non-null   str
 3   Place of Birth     37321 non-null   str
 4   Aliases            10639 non-null   str
 5   Titles             210870 non-null  str
 6   Other Information  70981 non-null   str
 7   Direct ID          210870 non-null  str
 8   Effective Date     60580 non-null   float64
 9   Entity Level       204448 non-null  str
 10  Expiration Date    51843 non-null   float64
 11  Gender             208221 non-null  str
 12  Name Source        210870 non-null  str
 13  Org PID            187644 non-null  float64
 14  Original ID        210870 non-null  int64
 15  Relationship       187644 non-null  str
 16  Sub Category       210870 non-null  str
 17  Address 1          210870 non-null  str
 18  Address 2          15530 non-null   str
 19  Address 3          5642 non-null    str
 20  Address 4          2269 non-null    str
 21  Address 5          997 non-null     str
 22  Address 6          458 non-null     str
 23  Address 7          218 non-null     str
 24  Address 8          109 non-null     str
 25  Address 9          53 non-null      str
 26  Address 10         25 non-null      str
 27  City               17 non-null      str
 28  State              8 non-null       str
 29  State Name         2 non-null       str
 30  Country            1 non-null       str
 31  Country Name       0 non-null       float64
 32  Postal Code        0 non-null       float64
dtypes: float64(5), int64(2), str(26)
memory usage: 53.1 MB

## **14. Convertors**

In [45]:
pd.read_csv('data/result.csv', encoding='utf-8')

C:\Users\Preet Kumar\AppData\Local\Temp\ipykernel_18616\2466651551.py:1: DtypeWarning: Columns (0: Address 8, 1: Address 9, 2: Address 10, 3: City, 4: State, 5: State Name, 6: Country) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('data/result.csv', encoding='utf-8')

,Entity ID,Name,Date of Birth,Place of Birth,Aliases,Titles,Other Information,Direct ID,Effective Date,Entity Level,...,Address 7,Address 8,Address 9,Address 10,City,State,State Name,Country,Country Name,Postal Code
0,1123115,"CHENEY, RICHARD BRUCE",1/30/1941,"Lincoln, Nebraska, United States","CHENEY, DICK",FORMER VICE PRESIDENT OF THE UNITED STATES (JA...,Career: Vice President of the United States (J...,https://accuity.worldcompliance.com/signin.asp...,1974.0,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1123443,"PARDEW, JAMES WILLIAM JR",2/5/1944,"Memphis, Tennessee, United States","PARDUE, JAMES",FORMER AMBASSADOR OF THE UNITED STATES TO BULG...,NickName: Jimmy; Career: Ambassador of the Uni...,https://accuity.worldcompliance.com/signin.asp...,2002.0,International,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1123445,"BAKER, HOWARD HENRY JR.",11/15/1925,"Huntsville, Tennessee, United States",NaN,FORMER AMBASSADOR OF THE UNITED STATES TO JAPA...,Career: Ambassador of the United States to Jap...,https://accuity.worldcompliance.com/signin.asp...,1977.0,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1123455,"MILES, RICHARD MONROE",1/8/1937,"Little Rock, Arkansas, United States",NaN,FORMER INTERIM CHARGE D'AFFAIRES OF THE UNITED...,Career: Interim Charge d'Affaires of the Unite...,https://accuity.worldcompliance.com/signin.asp...,1984.0,International,...,"111 AZADLIG AVE, BAKU, AZ, AZERBAIJAN, AZ1007","2201 C ST., NW, US, UNITED STATES, WASHINGTON,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1123456,"MILLER, THOMAS JOEL",12/9/1948,"Chicago, Illinois, United States","MILLER, TOM",FORMER AMBASSADOR OF THE UNITED STATES TO GREE...,Career: Ambassador of the United States to Gre...,https://accuity.worldcompliance.com/signin.asp...,1999.0,International,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210865,19694351,"JANOUSEK, DILLON",NaN,NaN,NaN,VICE PRESIDENT OF PRODUCTION OPERATIONS OF NOR...,Career: Vice President of Production Operation...,https://accuity.worldcompliance.com/signin.asp...,2023.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210866,19694352,"WILDER, JARED",2005,NaN,NaN,"SON OF TIFFANY SPANN-WILDER, MEMBER OF THE SOU...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210867,19694353,"SPANN, GENEVA",NaN,NaN,NaN,"MOTHER OF TIFFANY SPANN-WILDER, MEMBER OF THE ...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210868,19694358,"THAMES, CLEO",NaN,NaN,NaN,"MOTHER OF BILLY HOWARD THAMES, FORMER MEMBER O...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,State,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210869,19694359,"WILDER, JEFFERY",NaN,"Florence, South Carolina, United States",NaN,"HUSBAND OF TIFFANY SPANN-WILDER, MEMBER OF THE...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
def rename_col(name):
    if name == 'National':
        return 'Local'
    else:
        return name

In [47]:
pd.read_csv('data/result.csv', encoding='utf-8', converters={'Entity Level': rename_col})

C:\Users\Preet Kumar\AppData\Local\Temp\ipykernel_18616\2628316215.py:1: DtypeWarning: Columns (0: Address 8, 1: Address 9, 2: Address 10, 3: City, 4: State, 5: State Name, 6: Country) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('data/result.csv', encoding='utf-8', converters={'Entity Level': rename_col})

,Entity ID,Name,Date of Birth,Place of Birth,Aliases,Titles,Other Information,Direct ID,Effective Date,Entity Level,...,Address 7,Address 8,Address 9,Address 10,City,State,State Name,Country,Country Name,Postal Code
0,1123115,"CHENEY, RICHARD BRUCE",1/30/1941,"Lincoln, Nebraska, United States","CHENEY, DICK",FORMER VICE PRESIDENT OF THE UNITED STATES (JA...,Career: Vice President of the United States (J...,https://accuity.worldcompliance.com/signin.asp...,1974.0,Local,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1123443,"PARDEW, JAMES WILLIAM JR",2/5/1944,"Memphis, Tennessee, United States","PARDUE, JAMES",FORMER AMBASSADOR OF THE UNITED STATES TO BULG...,NickName: Jimmy; Career: Ambassador of the Uni...,https://accuity.worldcompliance.com/signin.asp...,2002.0,International,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1123445,"BAKER, HOWARD HENRY JR.",11/15/1925,"Huntsville, Tennessee, United States",NaN,FORMER AMBASSADOR OF THE UNITED STATES TO JAPA...,Career: Ambassador of the United States to Jap...,https://accuity.worldcompliance.com/signin.asp...,1977.0,Local,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1123455,"MILES, RICHARD MONROE",1/8/1937,"Little Rock, Arkansas, United States",NaN,FORMER INTERIM CHARGE D'AFFAIRES OF THE UNITED...,Career: Interim Charge d'Affaires of the Unite...,https://accuity.worldcompliance.com/signin.asp...,1984.0,International,...,"111 AZADLIG AVE, BAKU, AZ, AZERBAIJAN, AZ1007","2201 C ST., NW, US, UNITED STATES, WASHINGTON,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1123456,"MILLER, THOMAS JOEL",12/9/1948,"Chicago, Illinois, United States","MILLER, TOM",FORMER AMBASSADOR OF THE UNITED STATES TO GREE...,Career: Ambassador of the United States to Gre...,https://accuity.worldcompliance.com/signin.asp...,1999.0,International,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210865,19694351,"JANOUSEK, DILLON",NaN,NaN,NaN,VICE PRESIDENT OF PRODUCTION OPERATIONS OF NOR...,Career: Vice President of Production Operation...,https://accuity.worldcompliance.com/signin.asp...,2023.0,N/A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210866,19694352,"WILDER, JARED",2005,NaN,NaN,"SON OF TIFFANY SPANN-WILDER, MEMBER OF THE SOU...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,Local,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210867,19694353,"SPANN, GENEVA",NaN,NaN,NaN,"MOTHER OF TIFFANY SPANN-WILDER, MEMBER OF THE ...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,Local,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210868,19694358,"THAMES, CLEO",NaN,NaN,NaN,"MOTHER OF BILLY HOWARD THAMES, FORMER MEMBER O...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,State,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210869,19694359,"WILDER, JEFFERY",NaN,"Florence, South Carolina, United States",NaN,"HUSBAND OF TIFFANY SPANN-WILDER, MEMBER OF THE...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,Local,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## **15. na_values Parameter**

In [49]:
# Use to specifiy which kind of values treated as missing values, by default it is set to NaN but you can change it to any value.

# pd.read_csv('data/result.csv', na_values=['NA', 'Missing', 'Not Available'])

pd.read_csv('data/result.csv', na_values={'Entity Level': ['NA', 'Missing'], 'Place of Birth': ['Not Available']})

C:\Users\Preet Kumar\AppData\Local\Temp\ipykernel_18616\755506408.py:5: DtypeWarning: Columns (0: Address 8, 1: Address 9, 2: Address 10, 3: City, 4: State, 5: State Name, 6: Country) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('data/result.csv', na_values={'Entity Level': ['NA', 'Missing'], 'Place of Birth': ['Not Available']})

,Entity ID,Name,Date of Birth,Place of Birth,Aliases,Titles,Other Information,Direct ID,Effective Date,Entity Level,...,Address 7,Address 8,Address 9,Address 10,City,State,State Name,Country,Country Name,Postal Code
0,1123115,"CHENEY, RICHARD BRUCE",1/30/1941,"Lincoln, Nebraska, United States","CHENEY, DICK",FORMER VICE PRESIDENT OF THE UNITED STATES (JA...,Career: Vice President of the United States (J...,https://accuity.worldcompliance.com/signin.asp...,1974.0,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1123443,"PARDEW, JAMES WILLIAM JR",2/5/1944,"Memphis, Tennessee, United States","PARDUE, JAMES",FORMER AMBASSADOR OF THE UNITED STATES TO BULG...,NickName: Jimmy; Career: Ambassador of the Uni...,https://accuity.worldcompliance.com/signin.asp...,2002.0,International,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1123445,"BAKER, HOWARD HENRY JR.",11/15/1925,"Huntsville, Tennessee, United States",NaN,FORMER AMBASSADOR OF THE UNITED STATES TO JAPA...,Career: Ambassador of the United States to Jap...,https://accuity.worldcompliance.com/signin.asp...,1977.0,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1123455,"MILES, RICHARD MONROE",1/8/1937,"Little Rock, Arkansas, United States",NaN,FORMER INTERIM CHARGE D'AFFAIRES OF THE UNITED...,Career: Interim Charge d'Affaires of the Unite...,https://accuity.worldcompliance.com/signin.asp...,1984.0,International,...,"111 AZADLIG AVE, BAKU, AZ, AZERBAIJAN, AZ1007","2201 C ST., NW, US, UNITED STATES, WASHINGTON,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1123456,"MILLER, THOMAS JOEL",12/9/1948,"Chicago, Illinois, United States","MILLER, TOM",FORMER AMBASSADOR OF THE UNITED STATES TO GREE...,Career: Ambassador of the United States to Gre...,https://accuity.worldcompliance.com/signin.asp...,1999.0,International,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210865,19694351,"JANOUSEK, DILLON",NaN,NaN,NaN,VICE PRESIDENT OF PRODUCTION OPERATIONS OF NOR...,Career: Vice President of Production Operation...,https://accuity.worldcompliance.com/signin.asp...,2023.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210866,19694352,"WILDER, JARED",2005,NaN,NaN,"SON OF TIFFANY SPANN-WILDER, MEMBER OF THE SOU...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210867,19694353,"SPANN, GENEVA",NaN,NaN,NaN,"MOTHER OF TIFFANY SPANN-WILDER, MEMBER OF THE ...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210868,19694358,"THAMES, CLEO",NaN,NaN,NaN,"MOTHER OF BILLY HOWARD THAMES, FORMER MEMBER O...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,State,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210869,19694359,"WILDER, JEFFERY",NaN,"Florence, South Carolina, United States",NaN,"HUSBAND OF TIFFANY SPANN-WILDER, MEMBER OF THE...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## **16. Loading a huge dataset in chunks**

In [59]:
df_chunks = pd.read_csv('data/result.csv', chunksize=50000)

In [60]:
for chunk in df_chunks:
    print(chunk.shape)

C:\Users\Preet Kumar\AppData\Local\Temp\ipykernel_18616\4141624576.py:1: DtypeWarning: Columns (0: Address 6, 1: Address 7, 2: Address 8, 3: Address 9, 4: Address 10, 5: City, 6: State, 7: State Name, 8: Country) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in df_chunks:

(50000, 33)

C:\Users\Preet Kumar\AppData\Local\Temp\ipykernel_18616\4141624576.py:1: DtypeWarning: Columns (0: Address 6, 1: Address 7, 2: Address 8, 3: Address 9, 4: Address 10, 5: City) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in df_chunks:

(50000, 33)

C:\Users\Preet Kumar\AppData\Local\Temp\ipykernel_18616\4141624576.py:1: DtypeWarning: Columns (0: Address 7, 1: Address 8, 2: Address 9, 3: Address 10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in df_chunks:

(50000, 33)
(50000, 33)
(10870, 33)

C:\Users\Preet Kumar\AppData\Local\Temp\ipykernel_18616\4141624576.py:1: DtypeWarning: Columns (0: Address 6, 1: Address 7, 2: Address 8, 3: Address 9, 4: Address 10, 5: City, 6: State) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in df_chunks:

# Working with Excel

In [65]:
import pandas as pd

In [66]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   ---- ---------------------------------- 30.7/250.9 kB 660.6 kB/s eta 0:00:01
   ---- ---------------------------------- 30.7/250.9 kB 660.6 kB/s eta 0:00:01
   --------- ----------------------------- 61.4/250.9 kB 465.5 kB/s eta 0:00:01
   -------------- ------------------------ 92.2/250.9 kB 476.3 kB/s eta 0:00:01
   --------------- ---------------------- 102.4/250.9 kB 454.0 kB/s eta 0:00:01
   -------------------------- ----------- 174.1/250.9 kB 615.9 kB/s eta 0:00:01
   ---------------------------------- --- 225.3/250.9 kB 687.0 kB/s eta 0:00:01
   -------------------------------------- 250.9/250.9 kB 668.5 kB/s eta 0:00:00
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [67]:
import openpyxl

In [69]:
pd.read_excel('data/result.xlsx', engine='openpyxl')

,Entity ID,Name,Date of Birth,Place of Birth,Aliases,Titles,Other Information,Direct ID,Effective Date,Entity Level,...,Address 7,Address 8,Address 9,Address 10,City,State,State Name,Country,Country Name,Postal Code
0,1123115,"CHENEY, RICHARD BRUCE",1941-01-30 00:00:00,"Lincoln, Nebraska, United States","CHENEY, DICK",FORMER VICE PRESIDENT OF THE UNITED STATES (JA...,Career: Vice President of the United States (J...,https://accuity.worldcompliance.com/signin.asp...,1974.0,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1123443,"PARDEW, JAMES WILLIAM JR",1944-02-05 00:00:00,"Memphis, Tennessee, United States","PARDUE, JAMES",FORMER AMBASSADOR OF THE UNITED STATES TO BULG...,NickName: Jimmy; Career: Ambassador of the Uni...,https://accuity.worldcompliance.com/signin.asp...,2002.0,International,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1123445,"BAKER, HOWARD HENRY JR.",1925-11-15 00:00:00,"Huntsville, Tennessee, United States",NaN,FORMER AMBASSADOR OF THE UNITED STATES TO JAPA...,Career: Ambassador of the United States to Jap...,https://accuity.worldcompliance.com/signin.asp...,1977.0,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1123455,"MILES, RICHARD MONROE",1937-01-08 00:00:00,"Little Rock, Arkansas, United States",NaN,FORMER INTERIM CHARGE D'AFFAIRES OF THE UNITED...,Career: Interim Charge d'Affaires of the Unite...,https://accuity.worldcompliance.com/signin.asp...,1984.0,International,...,"111 AZADLIG AVE, BAKU, AZ, AZERBAIJAN, AZ1007","2201 C ST., NW, US, UNITED STATES, WASHINGTON,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1123456,"MILLER, THOMAS JOEL",1948-12-09 00:00:00,"Chicago, Illinois, United States","MILLER, TOM",FORMER AMBASSADOR OF THE UNITED STATES TO GREE...,Career: Ambassador of the United States to Gre...,https://accuity.worldcompliance.com/signin.asp...,1999.0,International,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210865,19694351,"JANOUSEK, DILLON",NaN,NaN,NaN,VICE PRESIDENT OF PRODUCTION OPERATIONS OF NOR...,Career: Vice President of Production Operation...,https://accuity.worldcompliance.com/signin.asp...,2023.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210866,19694352,"WILDER, JARED",2005,NaN,NaN,"SON OF TIFFANY SPANN-WILDER, MEMBER OF THE SOU...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210867,19694353,"SPANN, GENEVA",NaN,NaN,NaN,"MOTHER OF TIFFANY SPANN-WILDER, MEMBER OF THE ...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210868,19694358,"THAMES, CLEO",NaN,NaN,NaN,"MOTHER OF BILLY HOWARD THAMES, FORMER MEMBER O...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,State,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210869,19694359,"WILDER, JEFFERY",NaN,"Florence, South Carolina, United States",NaN,"HUSBAND OF TIFFANY SPANN-WILDER, MEMBER OF THE...",NaN,https://accuity.worldcompliance.com/signin.asp...,NaN,National,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## For selecting any sheet from the excel workbook

In [ ]:
pd.read_csv('data/result.csv', sheet_name='Sheet1', engine='openpyxl')

In [ ]:
%pip install polars

Collecting polars
  Downloading polars-1.44.1-py3-none-any.whl.metadata (11 kB)
Collecting polars-runtime-32==1.44.1 (from polars)
  Downloading polars_runtime_32-1.44.1-cp310-abi3-win_amd64.whl.metadata (1.5 kB)
Downloading polars-1.44.1-py3-none-any.whl (865 kB)
   ---------------------------------------- 0.0/865.2 kB ? eta -:--:--
   ---------------------------------------- 10.2/865.2 kB ? eta -:--:--
   - ------------------------------------- 30.7/865.2 kB 435.7 kB/s eta 0:00:02
   - ------------------------------------- 41.0/865.2 kB 279.3 kB/s eta 0:00:03
   --- ----------------------------------- 81.9/865.2 kB 456.6 kB/s eta 0:00:02
   --- ----------------------------------- 81.9/865.2 kB 456.6 kB/s eta 0:00:02
   --- ----------------------------------- 81.9/865.2 kB 456.6 kB/s eta 0:00:02
   --- ----------------------------------- 81.9/865.2 kB 456.6 kB/s eta 0:00:02
   --- ----------------------------------- 81.9/865.2 kB 456.6 kB/s eta 0:00:02
   -------- ----------------------------- 204.8/865.2 kB 478.0 kB/s eta 0:00:02
   -------- ----------------------------- 204.8/865.2 kB 478.0 kB/s eta 0:00:02
   -------- ----------------------------- 204.8/865.2 kB 478.0 kB/s eta 0:00:02
   --------- ---------------------------- 225.3/865.2 kB 393.1 kB/s eta 0:00:02
   ---------- --------------------------- 245.8/865.2 kB 418.3 kB/s eta 0:00:02
   ------------ ------------------------- 286.7/865.2 kB 442.4 kB/s eta 0:00:02
   ------------- ------------------------ 297.0/865.2 kB 447.3 kB/s eta 0:00:02
   -------------- ----------------------- 327.7/865.2 kB 461.4 kB/s eta 0:00:02
   ---------------- --------------------- 378.9/865.2 kB 481.3 kB/s eta 0:00:02
   ----------------- -------------------- 399.4/865.2 kB 497.6 kB/s eta 0:00:01
   ------------------- ------------------ 450.6/865.2 kB 521.7 kB/s eta 0:00:01
   --------------------- ---------------- 481.3/865.2 kB 528.7 kB/s eta 0:00:01
   ---------------------- --------------- 512.0/865.2 kB 526.0 kB/s eta 0:00:01
   ------------------------ ------------- 563.2/865.2 kB 553.0 kB/s eta 0:00:01
   -------------------------- ----------- 614.4/865.2 kB 568.4 kB/s eta 0:00:01
   --------------------------- ---------- 624.6/865.2 kB 561.6 kB/s eta 0:00:01
   ----------------------------- -------- 675.8/865.2 kB 575.3 kB/s eta 0:00:01
   ------------------------------- ------ 727.0/865.2 kB 588.0 kB/s eta 0:00:01
   -------------------------------- ----- 737.3/865.2 kB 588.7 kB/s eta 0:00:01
   ---------------------------------- --- 788.5/865.2 kB 600.0 kB/s eta 0:00:01
   ------------------------------------ - 839.7/865.2 kB 617.1 kB/s eta 0:00:01
   -------------------------------------  860.2/865.2 kB 618.1 kB/s eta 0:00:01
   -------------------------------------- 865.2/865.2 kB 601.2 kB/s eta 0:00:00
Downloading polars_runtime_32-1.44.1-cp310-abi3-win_amd64.whl (53.7 MB)
   ---------------------------------------- 0.0/53.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/53.7 MB 660.6 kB/s eta 0:01:22
   ---------------------------------------- 0.1/53.7 MB 919.0 kB/s eta 0:00:59
   ---------------------------------------- 0.1/53.7 MB 819.2 kB/s eta 0:01:06
   ---------------------------------------- 0.2/53.7 MB 766.6 kB/s eta 0:01:10
   ---------------------------------------- 0.2/53.7 MB 841.6 kB/s eta 0:01:04
   ---------------------------------------- 0.2/53.7 MB 875.2 kB/s eta 0:01:02
   ---------------------------------------- 0.3/53.7 MB 811.7 kB/s eta 0:01:06
   ---------------------------------------- 0.3/53.7 MB 855.7 kB/s eta 0:01:03
   ---------------------------------------- 0.3/53.7 MB 800.8 kB/s eta 0:01:07
   ---------------------------------------- 0.4/53.7 MB 829.7 kB/s eta 0:01:05
   ---------------------------------------- 0.4/53.7 MB 809.9 kB/s eta 0:01:06
   ---------------------------------------- 0.5/53.7 MB 779.5 kB/s eta 0:01:09
   ---------------------------------------- 0.5/53.7 MB 802.8 kB/s eta 0:01:07
   ---------------------------------------- 0.5/53.7 MB 811.7 kB/s eta 0:01:06
   ---------------------------------------- 0.6/53.7 MB 801.1 kB/s eta 0:01:07
   ---------------------------------------- 0.6/53.7 MB 802.1 kB/s eta 0:01:07
    --------------------------------------- 0.7/53.7 MB 835.1 kB/s eta 0:01:04
    --------------------------------------- 0.7/53.7 MB 825.0 kB/s eta 0:01:05
    --------------------------------------- 0.8/53.7 MB 825.1 kB/s eta 0:01:05
    --------------------------------------- 0.8/53.7 MB 816.6 kB/s eta 0:01:05
    --------------------------------------- 0.8/53.7 MB 829.4 kB/s eta 0:01:04
    --------------------------------------- 0.9/53.7 MB 834.3 kB/s eta 0:01:04
    --------------------------------------- 0.9/53.7 MB 826.4 kB/s eta 0:01:04
    --------------------------------------- 1.0/53.7 MB 843.6 kB/s eta 0:01:03
    --------------------------------------- 1.0/53.7 MB 847.5 kB/s eta 0:01:03
    --------------------------------------- 1.0/53.7 MB 829.8 kB/s eta 0:01:04
    --------------------------------------- 1.1/53.7 MB 836.9 kB/s eta 0:01:03
    --------------------------------------- 1.1/53.7 MB 850.7 kB/s eta 0:01:02
    --------------------------------------- 1.2/53.7 MB 830.3 kB/s eta 0:01:04
    --------------------------------------- 1.2/53.7 MB 848.0 kB/s eta 0:01:02
    --------------------------------------- 1.3/53.7 MB 850.4 kB/s eta 0:01:02
    --------------------------------------- 1.3/53.7 MB 849.4 kB/s eta 0:01:02
   - -------------------------------------- 1.4/53.7 MB 841.6 kB/s eta 0:01:03
   - -------------------------------------- 1.4/53.7 MB 848.7 kB/s eta 0:01:02
   - -------------------------------------- 1.4/53.7 MB 843.7 kB/s eta 0:01:02
   - -------------------------------------- 1.5/53.7 MB 850.4 kB/s eta 0:01:02
   - -------------------------------------- 1.5/53.7 MB 856.7 kB/s eta 0:01:01
   - -------------------------------------- 1.6/53.7 MB 855.2 kB/s eta 0:01:01
   - -------------------------------------- 1.6/53.7 MB 861.0 kB/s eta 0:01:01
   - -------------------------------------- 1.6/53.7 MB 859.6 kB/s eta 0:01:01
   - -------------------------------------- 1.7/53.7 MB 855.0 kB/s eta 0:01:01
   - -------------------------------------- 1.8/53.7 MB 855.4 kB/s eta 0:01:01
   - -------------------------------------- 1.8/53.7 MB 855.8 kB/s eta 0:01:01
   - -------------------------------------- 1.8/53.7 MB 840.7 kB/s eta 0:01:02
   - -------------------------------------- 1.9/53.7 MB 856.8 kB/s eta 0:01:01
   - -------------------------------------- 1.9/53.7 MB 851.1 kB/s eta 0:01:01
   - -------------------------------------- 2.0/53.7 MB 857.4 kB/s eta 0:01:01
   - -------------------------------------- 2.0/53.7 MB 853.3 kB/s eta 0:01:01
   - -------------------------------------- 2.1/53.7 MB 862.3 kB/s eta 0:01:00
   - -------------------------------------- 2.1/53.7 MB 858.3 kB/s eta 0:01:01
   - -------------------------------------- 2.1/53.7 MB 850.2 kB/s eta 0:01:01
   - -------------------------------------- 2.2/53.7 MB 860.2 kB/s eta 0:01:00
   - -------------------------------------- 2.2/53.7 MB 863.3 kB/s eta 0:01:00
   - -------------------------------------- 2.3/53.7 MB 859.5 kB/s eta 0:01:00
   - -------------------------------------- 2.3/53.7 MB 859.8 kB/s eta 0:01:00
   - -------------------------------------- 2.4/53.7 MB 862.4 kB/s eta 0:01:00
   - -------------------------------------- 2.4/53.7 MB 863.9 kB/s eta 0:01:00
   - -------------------------------------- 2.4/53.7 MB 863.0 kB/s eta 0:01:00
   - -------------------------------------- 2.5/53.7 MB 871.3 kB/s eta 0:00:59
   - -------------------------------------- 2.5/53.7 MB 860.7 kB/s eta 0:01:00
   - -------------------------------------- 2.5/53.7 MB 860.7 kB/s eta 0:01:00
   - -------------------------------------- 2.5/53.7 MB 860.7 kB/s eta 0:01:00
   - -------------------------------------- 2.5/53.7 MB 860.7 kB/s eta 0:01:00
   - -------------------------------------- 2.5/53.7 MB 860.7 kB/s eta 0:01:00
   - -------------------------------------- 2.5/53.7 MB 860.7 kB/s eta 0:01:00
   - -------------------------------------- 2.5/53.7 MB 860.7 kB/s eta 0:01:00
   - -------------------------------------- 2.5/53.7 MB 860.7 kB/s eta 0:01:00
   - -------------------------------------- 2.6/53.7 MB 790.8 kB/s eta 0:01:05
   - -------------------------------------- 2.6/53.7 MB 790.8 kB/s eta 0:01:05
   - -------------------------------------- 2.6/53.7 MB 790.8 kB/s eta 0:01:05
   - -------------------------------------- 2.7/53.7 MB 775.0 kB/s eta 0:01:06
   - -------------------------------------- 2.7/53.7 MB 775.0 kB/s eta 0:01:06
   -- ------------------------------------- 2.7/53.7 MB 773.0 kB/s eta 0:01:06
   -- ------------------------------------- 2.7/53.7 MB 768.9 kB/s eta 0:01:07
   -- ------------------------------------- 2.7/53.7 MB 764.1 kB/s eta 0:01:07
   -- ------------------------------------- 2.8/53.7 MB 762.2 kB/s eta 0:01:07
   -- ------------------------------------- 2.8/53.7 MB 764.1 kB/s eta 0:01:07
   -- ------------------------------------- 2.8/53.7 MB 762.7 kB/s eta 0:01:07
   -- ------------------------------------- 2.9/53.7 MB 758.6 kB/s eta 0:01:08
   -- ------------------------------------- 2.9/53.7 MB 760.2 kB/s eta 0:01:07
   -- ------------------------------------- 2.9/53.7 MB 761.6 kB/s eta 0:01:07
   -- ------------------------------------- 3.0/53.7 MB 757.2 kB/s eta 0:01:07
   -- ------------------------------------- 3.0/53.7 MB 756.9 kB/s eta 0:01:08
   -- ------------------------------------- 3.0/53.7 MB 757.8 kB/s eta 0:01:07
   -- ------------------------------------- 3.1/53.7 MB 756.5 kB/s eta 0:01:07
   -- ------------------------------------- 3.1/53.7 MB 755.1 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 756.4 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.2/53.7 MB 757.7 kB/s eta 0:01:07
   -- ------------------------------------- 3.3/53.7 MB 561.5 kB/s eta 0:01:30
   -- ------------------------------------- 3.3/53.7 MB 561.5 kB/s eta 0:01:30
   -- ------------------------------------- 3.3/53.7 MB 561.5 kB/s eta 0:01:30
   -- ------------------------------------- 3.3/53.7 MB 561.5 kB/s eta 0:01:30
   -- ------------------------------------- 3.3/53.7 MB 561.5 kB/s eta 0:01:30
   -- ------------------------------------- 3.3/53.7 MB 561.5 kB/s eta 0:01:30
   -- ------------------------------------- 3.3/53.7 MB 561.5 kB/s eta 0:01:30
   -- ------------------------------------- 3.3/53.7 MB 535.0 kB/s eta 0:01:35
   -- ------------------------------------- 3.3/53.7 MB 537.3 kB/s eta 0:01:34
   -- ------------------------------------- 3.3/53.7 MB 537.3 kB/s eta 0:01:34
   -- ------------------------------------- 3.3/53.7 MB 537.3 kB/s eta 0:01:34
   -- ------------------------------------- 3.3/53.7 MB 537.3 kB/s eta 0:01:34
   -- ------------------------------------- 3.3/53.7 MB 525.9 kB/s eta 0:01:36
   -- ------------------------------------- 3.3/53.7 MB 525.9 kB/s eta 0:01:36
   -- ------------------------------------- 3.3/53.7 MB 525.9 kB/s eta 0:01:36
   -- ------------------------------------- 3.3/53.7 MB 517.3 kB/s eta 0:01:38
   -- ------------------------------------- 3.4/53.7 MB 513.0 kB/s eta 0:01:39
   -- ------------------------------------- 3.4/53.7 MB 513.0 kB/s eta 0:01:39
   -- ------------------------------------- 3.4/53.7 MB 511.3 kB/s eta 0:01:39
   -- ------------------------------------- 3.4/53.7 MB 509.2 kB/s eta 0:01:39
   -- ------------------------------------- 3.4/53.7 MB 508.7 kB/s eta 0:01:39
   -- ------------------------------------- 3.5/53.7 MB 509.7 kB/s eta 0:01:39
   -- ------------------------------------- 3.5/53.7 MB 509.6 kB/s eta 0:01:39
   -- ------------------------------------- 3.5/53.7 MB 512.4 kB/s eta 0:01:38
   -- ------------------------------------- 3.5/53.7 MB 512.4 kB/s eta 0:01:38
   -- ------------------------------------- 3.5/53.7 MB 512.4 kB/s eta 0:01:38
   -- ------------------------------------- 3.5/53.7 MB 512.4 kB/s eta 0:01:38
   -- ------------------------------------- 3.5/53.7 MB 512.4 kB/s eta 0:01:38
   -- ------------------------------------- 3.5/53.7 MB 512.4 kB/s eta 0:01:38
   -- ------------------------------------- 3.6/53.7 MB 510.2 kB/s eta 0:01:39
   -- ------------------------------------- 3.7/53.7 MB 514.0 kB/s eta 0:01:38
   -- ------------------------------------- 3.7/53.7 MB 514.0 kB/s eta 0:01:38
   -- ------------------------------------- 3.7/53.7 MB 511.3 kB/s eta 0:01:38
   -- ------------------------------------- 3.7/53.7 MB 507.2 kB/s eta 0:01:39
   -- ------------------------------------- 3.8/53.7 MB 508.2 kB/s eta 0:01:39
   -- ------------------------------------- 3.8/53.7 MB 510.5 kB/s eta 0:01:38
   -- ------------------------------------- 3.8/53.7 MB 510.5 kB/s eta 0:01:38
   -- ------------------------------------- 3.8/53.7 MB 508.2 kB/s eta 0:01:39
   -- ------------------------------------- 3.9/53.7 MB 509.2 kB/s eta 0:01:38
   -- ------------------------------------- 3.9/53.7 MB 509.2 kB/s eta 0:01:38
   -- ------------------------------------- 3.9/53.7 MB 506.6 kB/s eta 0:01:39
   -- ------------------------------------- 3.9/53.7 MB 506.6 kB/s eta 0:01:39
   -- ------------------------------------- 3.9/53.7 MB 501.8 kB/s eta 0:01:40
   -- ------------------------------------- 3.9/53.7 MB 501.8 kB/s eta 0:01:40
   -- ------------------------------------- 3.9/53.7 MB 501.8 kB/s eta 0:01:40
   -- ------------------------------------- 3.9/53.7 MB 501.8 kB/s eta 0:01:40
   -- ------------------------------------- 3.9/53.7 MB 501.8 kB/s eta 0:01:40
   -- ------------------------------------- 3.9/53.7 MB 489.6 kB/s eta 0:01:42
   -- ------------------------------------- 4.0/53.7 MB 497.9 kB/s eta 0:01:40
   -- ------------------------------------- 4.0/53.7 MB 497.9 kB/s eta 0:01:40
   -- ------------------------------------- 4.0/53.7 MB 495.9 kB/s eta 0:01:41
   --- ------------------------------------ 4.0/53.7 MB 496.6 kB/s eta 0:01:41
   --- ------------------------------------ 4.1/53.7 MB 494.1 kB/s eta 0:01:41
   --- ------------------------------------ 4.1/53.7 MB 493.7 kB/s eta 0:01:41
   --- ------------------------------------ 4.1/53.7 MB 494.6 kB/s eta 0:01:41
   --- ------------------------------------ 4.1/53.7 MB 493.3 kB/s eta 0:01:41
   --- ------------------------------------ 4.1/53.7 MB 492.7 kB/s eta 0:01:41
   --- ------------------------------------ 4.2/53.7 MB 493.4 kB/s eta 0:01:41
   --- ------------------------------------ 4.2/53.7 MB 490.6 kB/s eta 0:01:41
   --- ------------------------------------ 4.2/53.7 MB 491.2 kB/s eta 0:01:41
   --- ------------------------------------ 4.2/53.7 MB 490.6 kB/s eta 0:01:41
   --- ------------------------------------ 4.2/53.7 MB 489.8 kB/s eta 0:01:41
   --- ------------------------------------ 4.2/53.7 MB 489.8 kB/s eta 0:01:41
   --- ------------------------------------ 4.3/53.7 MB 490.1 kB/s eta 0:01:41
   --- ------------------------------------ 4.3/53.7 MB 488.6 kB/s eta 0:01:42
   --- ------------------------------------ 4.3/53.7 MB 487.8 kB/s eta 0:01:42
   --- ------------------------------------ 4.4/53.7 MB 489.2 kB/s eta 0:01:41
   --- ------------------------------------ 4.4/53.7 MB 489.8 kB/s eta 0:01:41
   --- ------------------------------------ 4.4/53.7 MB 489.0 kB/s eta 0:01:41
   --- ------------------------------------ 4.4/53.7 MB 489.0 kB/s eta 0:01:41
   --- ------------------------------------ 4.5/53.7 MB 488.7 kB/s eta 0:01:41
   --- ------------------------------------ 4.5/53.7 MB 488.2 kB/s eta 0:01:41
   --- ------------------------------------ 4.5/53.7 MB 487.9 kB/s eta 0:01:41
   --- ------------------------------------ 4.5/53.7 MB 488.7 kB/s eta 0:01:41
   --- ------------------------------------ 4.5/53.7 MB 488.5 kB/s eta 0:01:41
   --- ------------------------------------ 4.5/53.7 MB 487.9 kB/s eta 0:01:41
   --- ------------------------------------ 4.6/53.7 MB 488.8 kB/s eta 0:01:41
   --- ------------------------------------ 4.6/53.7 MB 487.7 kB/s eta 0:01:41
   --- ------------------------------------ 4.6/53.7 MB 487.7 kB/s eta 0:01:41
   --- ------------------------------------ 4.6/53.7 MB 488.3 kB/s eta 0:01:41
   --- ------------------------------------ 4.7/53.7 MB 488.3 kB/s eta 0:01:41
   --- ------------------------------------ 4.7/53.7 MB 488.8 kB/s eta 0:01:41
   --- ------------------------------------ 4.7/53.7 MB 488.1 kB/s eta 0:01:41
   --- ------------------------------------ 4.7/53.7 MB 487.6 kB/s eta 0:01:41
   --- ------------------------------------ 4.8/53.7 MB 488.1 kB/s eta 0:01:41
   --- ------------------------------------ 4.8/53.7 MB 487.4 kB/s eta 0:01:41
   --- ------------------------------------ 4.8/53.7 MB 488.2 kB/s eta 0:01:41
   --- ------------------------------------ 4.8/53.7 MB 487.9 kB/s eta 0:01:41
   --- ------------------------------------ 4.9/53.7 MB 487.9 kB/s eta 0:01:41
   --- ------------------------------------ 4.9/53.7 MB 488.4 kB/s eta 0:01:40
   --- ------------------------------------ 4.9/53.7 MB 488.5 kB/s eta 0:01:40
   --- ------------------------------------ 4.9/53.7 MB 488.5 kB/s eta 0:01:40
   --- ------------------------------------ 4.9/53.7 MB 488.5 kB/s eta 0:01:40
   --- ------------------------------------ 4.9/53.7 MB 488.5 kB/s eta 0:01:40
   --- ------------------------------------ 4.9/53.7 MB 488.5 kB/s eta 0:01:40
   --- ------------------------------------ 4.9/53.7 MB 488.5 kB/s eta 0:01:40

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting polars
  Using cached polars-1.44.1-py3-none-any.whl.metadata (11 kB)
Collecting polars-runtime-32==1.44.1 (from polars)
  Using cached polars_runtime_32-1.44.1-cp310-abi3-win_amd64.whl.metadata (1.5 kB)
Using cached polars-1.44.1-py3-none-any.whl (865 kB)
Downloading polars_runtime_32-1.44.1-cp310-abi3-win_amd64.whl (53.7 MB)
   ---------------------------------------- 0.0/53.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/53.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/53.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/53.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/53.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/53.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/53.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/53.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/53.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/53.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/53.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/53.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/53.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/53.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/53.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/53.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/53.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/53.7 MB 46.8 kB/s eta 0:19:08
   ---------------------------------------- 0.0/53.7 MB 46.8 kB/s eta 0:19:08
   ---------------------------------------- 0.0/53.7 MB 46.8 kB/s eta 0:19:08
   ---------------------------------------- 0.0/53.7 MB 46.8 kB/s eta 0:19:08
   ---------------------------------------- 0.1/53.7 MB 48.5 kB/s eta 0:18:26
   ---------------------------------------- 0.1/53.7 MB 48.5 kB/s eta 0:18:26
   ---------------------------------------- 0.1/53.7 MB 52.8 kB/s eta 0:16:56
   ---------------------------------------- 0.1/53.7 MB 52.8 kB/s eta 0:16:56
   ---------------------------------------- 0.1/53.7 MB 52.8 kB/s eta 0:16:56
   ---------------------------------------- 0.1/53.7 MB 52.8 kB/s eta 0:16:56
   ---------------------------------------- 0.1/53.7 MB 52.8 kB/s eta 0:16:56
   ---------------------------------------- 0.1/53.7 MB 52.8 kB/s eta 0:16:56
   ---------------------------------------- 0.1/53.7 MB 52.8 kB/s eta 0:16:56
   ---------------------------------------- 0.1/53.7 MB 52.8 kB/s eta 0:16:56
   ---------------------------------------- 0.1/53.7 MB 44.2 kB/s eta 0:20:15
   ---------------------------------------- 0.1/53.7 MB 57.0 kB/s eta 0:15:42
   ---------------------------------------- 0.1/53.7 MB 57.0 kB/s eta 0:15:42
   ---------------------------------------- 0.1/53.7 MB 57.0 kB/s eta 0:15:42
   ---------------------------------------- 0.1/53.7 MB 57.0 kB/s eta 0:15:42
   ---------------------------------------- 0.1/53.7 MB 57.0 kB/s eta 0:15:42
   ---------------------------------------- 0.1/53.7 MB 57.0 kB/s eta 0:15:42
   ---------------------------------------- 0.1/53.7 MB 57.0 kB/s eta 0:15:42
   ---------------------------------------- 0.1/53.7 MB 57.0 kB/s eta 0:15:42
   ---------------------------------------- 0.1/53.7 MB 57.0 kB/s eta 0:15:42
   ---------------------------------------- 0.1/53.7 MB 57.0 kB/s eta 0:15:42
   ---------------------------------------- 0.1/53.7 MB 47.6 kB/s eta 0:18:48
   ---------------------------------------- 0.1/53.7 MB 47.6 kB/s eta 0:18:48
   ---------------------------------------- 0.1/53.7 MB 47.6 kB/s eta 0:18:48
   ---------------------------------------- 0.1/53.7 MB 47.6 kB/s eta 0:18:48
   ---------------------------------------- 0.1/53.7 MB 47.6 kB/s eta 0:18:48
   ---------------------------------------- 0.1/53.7 MB 47.6 kB/s eta 0:18:48
   ---------------------------------------- 0.1/53.7 MB 47.6 kB/s eta 0:18:48
   ---------------------------------------- 0.1/53.7 MB 47.6 kB/s eta 0:18:48
   ---------------------------------------- 0.1/53.7 MB 47.6 kB/s eta 0:18:48
   ---------------------------------------- 0.1/53.7 MB 47.6 kB/s eta 0:18:48
   ---------------------------------------- 0.1/53.7 MB 47.6 kB/s eta 0:18:48
   ---------------------------------------- 0.1/53.7 MB 47.6 kB/s eta 0:18:48
   ---------------------------------------- 0.1/53.7 MB 45.1 kB/s eta 0:19:50
   ---------------------------------------- 0.1/53.7 MB 45.1 kB/s eta 0:19:50
   ---------------------------------------- 0.1/53.7 MB 45.1 kB/s eta 0:19:50
   ---------------------------------------- 0.1/53.7 MB 45.1 kB/s eta 0:19:50
   ---------------------------------------- 0.1/53.7 MB 45.1 kB/s eta 0:19:50
   ---------------------------------------- 0.1/53.7 MB 44.7 kB/s eta 0:19:59
   ---------------------------------------- 0.1/53.7 MB 44.7 kB/s eta 0:19:59
   ---------------------------------------- 0.1/53.7 MB 44.7 kB/s eta 0:19:59
   ---------------------------------------- 0.1/53.7 MB 44.7 kB/s eta 0:19:59
   ---------------------------------------- 0.1/53.7 MB 44.7 kB/s eta 0:19:59
   ---------------------------------------- 0.2/53.7 MB 47.8 kB/s eta 0:18:41
   ---------------------------------------- 0.2/53.7 MB 47.8 kB/s eta 0:18:41
   ---------------------------------------- 0.2/53.7 MB 47.8 kB/s eta 0:18:41
   ---------------------------------------- 0.2/53.7 MB 47.8 kB/s eta 0:18:41
   ---------------------------------------- 0.2/53.7 MB 47.8 kB/s eta 0:18:41
   ---------------------------------------- 0.2/53.7 MB 47.8 kB/s eta 0:18:41
   ---------------------------------------- 0.2/53.7 MB 47.8 kB/s eta 0:18:41
   ---------------------------------------- 0.2/53.7 MB 47.8 kB/s eta 0:18:41
   ---------------------------------------- 0.2/53.7 MB 47.8 kB/s eta 0:18:41
   ---------------------------------------- 0.2/53.7 MB 47.8 kB/s eta 0:18:41
   ---------------------------------------- 0.2/53.7 MB 47.8 kB/s eta 0:18:41
   ---------------------------------------- 0.2/53.7 MB 47.8 kB/s eta 0:18:41
   ---------------------------------------- 0.2/53.7 MB 47.8 kB/s eta 0:18:41
   ---------------------------------------- 0.2/53.7 MB 47.8 kB/s eta 0:18:41
   ---------------------------------------- 0.2/53.7 MB 47.8 kB/s eta 0:18:41
   ---------------------------------------- 0.2/53.7 MB 47.8 kB/s eta 0:18:41
   ---------------------------------------- 0.2/53.7 MB 47.8 kB/s eta 0:18:41
   ---------------------------------------- 0.2/53.7 MB 47.8 kB/s eta 0:18:41
   ---------------------------------------- 0.2/53.7 MB 47.8 kB/s eta 0:18:41
   ---------------------------------------- 0.2/53.7 MB 47.8 kB/s eta 0:18:41
   ---------------------------------------- 0.2/53.7 MB 41.8 kB/s eta 0:21:22
   ---------------------------------------- 0.2/53.7 MB 41.8 kB/s eta 0:21:22
   ---------------------------------------- 0.2/53.7 MB 41.8 kB/s eta 0:21:22
   ---------------------------------------- 0.2/53.7 MB 43.0 kB/s eta 0:20:45
   ---------------------------------------- 0.2/53.7 MB 43.0 kB/s eta 0:20:45
   ---------------------------------------- 0.2/53.7 MB 43.0 kB/s eta 0:20:45
   ---------------------------------------- 0.2/53.7 MB 43.0 kB/s eta 0:20:45
   ---------------------------------------- 0.2/53.7 MB 43.0 kB/s eta 0:20:45
   ---------------------------------------- 0.2/53.7 MB 43.0 kB/s eta 0:20:45
   ---------------------------------------- 0.2/53.7 MB 44.6 kB/s eta 0:19:59
   ---------------------------------------- 0.2/53.7 MB 44.6 kB/s eta 0:19:59
   ---------------------------------------- 0.2/53.7 MB 44.6 kB/s eta 0:19:59
   ---------------------------------------- 0.2/53.7 MB 44.6 kB/s eta 0:19:59
   ---------------------------------------- 0.2/53.7 MB 44.6 kB/s eta 0:19:59
   ---------------------------------------- 0.2/53.7 MB 44.6 kB/s eta 0:19:59
   ---------------------------------------- 0.2/53.7 MB 44.6 kB/s eta 0:19:59
   ---------------------------------------- 0.2/53.7 MB 44.6 kB/s eta 0:19:59
   ---------------------------------------- 0.2/53.7 MB 43.3 kB/s eta 0:20:37
   ---------------------------------------- 0.2/53.7 MB 43.3 kB/s eta 0:20:37
   ---------------------------------------- 0.2/53.7 MB 43.3 kB/s eta 0:20:37
   ---------------------------------------- 0.2/53.7 MB 43.3 kB/s eta 0:20:37
   ---------------------------------------- 0.2/53.7 MB 43.3 kB/s eta 0:20:37
   ---------------------------------------- 0.2/53.7 MB 43.3 kB/s eta 0:20:37
   ---------------------------------------- 0.2/53.7 MB 43.3 kB/s eta 0:20:37
   ---------------------------------------- 0.2/53.7 MB 44.4 kB/s eta 0:20:06
   ---------------------------------------- 0.2/53.7 MB 44.4 kB/s eta 0:20:06
   ---------------------------------------- 0.2/53.7 MB 44.4 kB/s eta 0:20:06
   ---------------------------------------- 0.2/53.7 MB 44.4 kB/s eta 0:20:06
   ---------------------------------------- 0.3/53.7 MB 46.7 kB/s eta 0:19:06
   ---------------------------------------- 0.3/53.7 MB 46.7 kB/s eta 0:19:06
   ---------------------------------------- 0.3/53.7 MB 46.7 kB/s eta 0:19:06
   ---------------------------------------- 0.3/53.7 MB 46.7 kB/s eta 0:19:06
   ---------------------------------------- 0.3/53.7 MB 47.1 kB/s eta 0:18:56
   ---------------------------------------- 0.3/53.7 MB 47.1 kB/s eta 0:18:56
   ---------------------------------------- 0.3/53.7 MB 47.1 kB/s eta 0:18:56
   ---------------------------------------- 0.3/53.7 MB 47.1 kB/s eta 0:18:56
   ---------------------------------------- 0.3/53.7 MB 49.2 kB/s eta 0:18:07
   ---------------------------------------- 0.3/53.7 MB 49.2 kB/s eta 0:18:07
   ---------------------------------------- 0.3/53.7 MB 49.2 kB/s eta 0:18:07
   ---------------------------------------- 0.3/53.7 MB 49.6 kB/s eta 0:17:57
   ---------------------------------------- 0.3/53.7 MB 49.6 kB/s eta 0:17:57
   ---------------------------------------- 0.3/53.7 MB 49.6 kB/s eta 0:17:57
   ---------------------------------------- 0.3/53.7 MB 49.6 kB/s eta 0:17:57
   ---------------------------------------- 0.3/53.7 MB 51.7 kB/s eta 0:17:12
   ---------------------------------------- 0.3/53.7 MB 51.7 kB/s eta 0:17:12
   ---------------------------------------- 0.3/53.7 MB 54.2 kB/s eta 0:16:25
   ---------------------------------------- 0.3/53.7 MB 54.2 kB/s eta 0:16:25
   ---------------------------------------- 0.3/53.7 MB 54.2 kB/s eta 0:16:25
   ---------------------------------------- 0.3/53.7 MB 54.5 kB/s eta 0:16:20
   ---------------------------------------- 0.3/53.7 MB 54.5 kB/s eta 0:16:20
   ---------------------------------------- 0.3/53.7 MB 54.5 kB/s eta 0:16:20
   ---------------------------------------- 0.4/53.7 MB 56.6 kB/s eta 0:15:42
   ---------------------------------------- 0.4/53.7 MB 56.6 kB/s eta 0:15:42
   ---------------------------------------- 0.4/53.7 MB 56.6 kB/s eta 0:15:42
   ---------------------------------------- 0.4/53.7 MB 56.6 kB/s eta 0:15:42
   ---------------------------------------- 0.4/53.7 MB 56.6 kB/s eta 0:15:42
   ---------------------------------------- 0.4/53.7 MB 56.6 kB/s eta 0:15:42
   ---------------------------------------- 0.4/53.7 MB 56.6 kB/s eta 0:15:42
   ---------------------------------------- 0.4/53.7 MB 56.6 kB/s eta 0:15:42
   ---------------------------------------- 0.4/53.7 MB 55.1 kB/s eta 0:16:08
   ---------------------------------------- 0.4/53.7 MB 55.1 kB/s eta 0:16:08
   ---------------------------------------- 0.4/53.7 MB 55.1 kB/s eta 0:16:08
   ---------------------------------------- 0.4/53.7 MB 55.1 kB/s eta 0:16:08
   ---------------------------------------- 0.4/53.7 MB 55.1 kB/s eta 0:16:08
   ---------------------------------------- 0.4/53.7 MB 59.3 kB/s eta 0:14:59
   ---------------------------------------- 0.4/53.7 MB 59.3 kB/s eta 0:14:59
   ---------------------------------------- 0.4/53.7 MB 59.3 kB/s eta 0:14:59
   ---------------------------------------- 0.4/53.7 MB 59.3 kB/s eta 0:14:59
   ---------------------------------------- 0.4/53.7 MB 58.9 kB/s eta 0:15:05
   ---------------------------------------- 0.4/53.7 MB 58.9 kB/s eta 0:15:05
   ---------------------------------------- 0.4/53.7 MB 58.9 kB/s eta 0:15:05
   ---------------------------------------- 0.5/53.7 MB 60.7 kB/s eta 0:14:37
   ---------------------------------------- 0.5/53.7 MB 61.4 kB/s eta 0:14:28
   ---------------------------------------- 0.5/53.7 MB 61.4 kB/s eta 0:14:28
   ---------------------------------------- 0.5/53.7 MB 63.3 kB/s eta 0:14:01
   ---------------------------------------- 0.5/53.7 MB 63.3 kB/s eta 0:14:01
   ---------------------------------------- 0.5/53.7 MB 65.3 kB/s eta 0:13:36
   ---------------------------------------- 0.5/53.7 MB 65.3 kB/s eta 0:13:36
   ---------------------------------------- 0.5/53.7 MB 65.9 kB/s eta 0:13:27
   ---------------------------------------- 0.5/53.7 MB 65.9 kB/s eta 0:13:27
   ---------------------------------------- 0.5/53.7 MB 67.7 kB/s eta 0:13:06
   ---------------------------------------- 0.5/53.7 MB 67.7 kB/s eta 0:13:06
   ---------------------------------------- 0.5/53.7 MB 68.2 kB/s eta 0:13:01
   ---------------------------------------- 0.5/53.7 MB 68.2 kB/s eta 0:13:01
   ---------------------------------------- 0.6/53.7 MB 69.9 kB/s eta 0:12:40
   ---------------------------------------- 0.6/53.7 MB 71.8 kB/s eta 0:12:20
   ---------------------------------------- 0.6/53.7 MB 71.8 kB/s eta 0:12:20
   ---------------------------------------- 0.6/53.7 MB 72.4 kB/s eta 0:12:14
   ---------------------------------------- 0.6/53.7 MB 72.4 kB/s eta 0:12:14
   ---------------------------------------- 0.6/53.7 MB 74.1 kB/s eta 0:11:57
   ---------------------------------------- 0.6/53.7 MB 74.6 kB/s eta 0:11:52
   ---------------------------------------- 0.6/53.7 MB 74.6 kB/s eta 0:11:52
   ---------------------------------------- 0.6/53.7 MB 76.4 kB/s eta 0:11:35
   ---------------------------------------- 0.6/53.7 MB 76.4 kB/s eta 0:11:35
   ---------------------------------------- 0.7/53.7 MB 78.1 kB/s eta 0:11:20
    --------------------------------------- 0.7/53.7 MB 78.6 kB/s eta 0:11:15
    --------------------------------------- 0.7/53.7 MB 78.6 kB/s eta 0:11:15
    --------------------------------------- 0.7/53.7 MB 79.8 kB/s eta 0:11:04
    --------------------------------------- 0.7/53.7 MB 79.8 kB/s eta 0:11:04
    --------------------------------------- 0.7/53.7 MB 79.8 kB/s eta 0:11:04
    --------------------------------------- 0.7/53.7 MB 79.8 kB/s eta 0:11:04
    --------------------------------------- 0.7/53.7 MB 79.8 kB/s eta 0:11:04
    --------------------------------------- 0.7/53.7 MB 79.8 kB/s eta 0:11:04
    --------------------------------------- 0.7/53.7 MB 79.8 kB/s eta 0:11:04
    --------------------------------------- 0.7/53.7 MB 79.8 kB/s eta 0:11:04
    --------------------------------------- 0.7/53.7 MB 79.8 kB/s eta 0:11:04
    --------------------------------------- 0.7/53.7 MB 81.9 kB/s eta 0:10:47
    --------------------------------------- 0.7/53.7 MB 81.9 kB/s eta 0:10:47
    --------------------------------------- 0.7/53.7 MB 81.9 kB/s eta 0:10:47
    --------------------------------------- 0.7/53.7 MB 81.9 kB/s eta 0:10:47
    --------------------------------------- 0.7/53.7 MB 81.9 kB/s eta 0:10:47
    --------------------------------------- 0.7/53.7 MB 81.9 kB/s eta 0:10:47
    --------------------------------------- 0.7/53.7 MB 81.9 kB/s eta 0:10:47
    --------------------------------------- 0.7/53.7 MB 81.9 kB/s eta 0:10:47
    --------------------------------------- 0.7/53.7 MB 81.9 kB/s eta 0:10:47
    --------------------------------------- 0.7/53.7 MB 81.9 kB/s eta 0:10:47
    --------------------------------------- 0.7/53.7 MB 81.9 kB/s eta 0:10:47
    --------------------------------------- 0.7/53.7 MB 81.9 kB/s eta 0:10:47
    --------------------------------------- 0.7/53.7 MB 81.9 kB/s eta 0:10:47
    --------------------------------------- 0.7/53.7 MB 81.9 kB/s eta 0:10:47
    --------------------------------------- 0.7/53.7 MB 81.9 kB/s eta 0:10:47
    --------------------------------------- 0.7/53.7 MB 81.9 kB/s eta 0:10:47
    --------------------------------------- 0.7/53.7 MB 81.9 kB/s eta 0:10:47
    --------------------------------------- 0.7/53.7 MB 81.9 kB/s eta 0:10:47
    --------------------------------------- 0.7/53.7 MB 81.9 kB/s eta 0:10:47
    --------------------------------------- 0.7/53.7 MB 81.9 kB/s eta 0:10:47
    --------------------------------------- 0.7/53.7 MB 81.9 kB/s eta 0:10:47
    --------------------------------------- 0.7/53.7 MB 81.9 kB/s eta 0:10:47
    --------------------------------------- 0.8/53.7 MB 74.2 kB/s eta 0:11:54
    --------------------------------------- 0.8/53.7 MB 74.2 kB/s eta 0:11:54
    --------------------------------------- 0.8/53.7 MB 74.2 kB/s eta 0:11:54
    --------------------------------------- 0.8/53.7 MB 74.2 kB/s eta 0:11:54
    --------------------------------------- 0.8/53.7 MB 74.2 kB/s eta 0:11:54
    --------------------------------------- 0.8/53.7 MB 74.2 kB/s eta 0:11:54
    --------------------------------------- 0.8/53.7 MB 74.2 kB/s eta 0:11:54
    --------------------------------------- 0.8/53.7 MB 74.2 kB/s eta 0:11:54
    --------------------------------------- 0.8/53.7 MB 74.2 kB/s eta 0:11:54
    --------------------------------------- 0.8/53.7 MB 72.9 kB/s eta 0:12:06
    --------------------------------------- 0.8/53.7 MB 72.9 kB/s eta 0:12:06
    --------------------------------------- 0.8/53.7 MB 72.9 kB/s eta 0:12:06
    --------------------------------------- 0.8/53.7 MB 72.9 kB/s eta 0:12:06
    --------------------------------------- 0.8/53.7 MB 72.9 kB/s eta 0:12:06
    --------------------------------------- 0.8/53.7 MB 72.9 kB/s eta 0:12:06
    --------------------------------------- 0.8/53.7 MB 72.0 kB/s eta 0:12:16
    --------------------------------------- 0.8/53.7 MB 72.0 kB/s eta 0:12:16
    --------------------------------------- 0.8/53.7 MB 72.0 kB/s eta 0:12:16
    --------------------------------------- 0.8/53.7 MB 72.0 kB/s eta 0:12:16
    --------------------------------------- 0.8/53.7 MB 72.0 kB/s eta 0:12:16
    --------------------------------------- 0.8/53.7 MB 72.0 kB/s eta 0:12:16
    --------------------------------------- 0.8/53.7 MB 71.8 kB/s eta 0:12:17
    --------------------------------------- 0.8/53.7 MB 71.8 kB/s eta 0:12:17
    --------------------------------------- 0.8/53.7 MB 71.8 kB/s eta 0:12:17
    --------------------------------------- 0.8/53.7 MB 72.5 kB/s eta 0:12:10
    --------------------------------------- 0.8/53.7 MB 72.5 kB/s eta 0:12:10
    --------------------------------------- 0.8/53.7 MB 72.5 kB/s eta 0:12:10
    --------------------------------------- 0.8/53.7 MB 72.5 kB/s eta 0:12:10
    --------------------------------------- 0.8/53.7 MB 72.1 kB/s eta 0:12:13
    --------------------------------------- 0.8/53.7 MB 72.1 kB/s eta 0:12:13
    --------------------------------------- 0.8/53.7 MB 72.1 kB/s eta 0:12:13
    --------------------------------------- 0.9/53.7 MB 72.9 kB/s eta 0:12:05
    --------------------------------------- 0.9/53.7 MB 72.9 kB/s eta 0:12:05
    --------------------------------------- 0.9/53.7 MB 72.9 kB/s eta 0:12:05
    --------------------------------------- 0.9/53.7 MB 72.9 kB/s eta 0:12:05
    --------------------------------------- 0.9/53.7 MB 72.8 kB/s eta 0:12:06
    --------------------------------------- 0.9/53.7 MB 72.8 kB/s eta 0:12:06
    --------------------------------------- 0.9/53.7 MB 72.8 kB/s eta 0:12:06
    --------------------------------------- 0.9/53.7 MB 72.8 kB/s eta 0:12:06
    --------------------------------------- 0.9/53.7 MB 72.8 kB/s eta 0:12:06
    --------------------------------------- 0.9/53.7 MB 72.8 kB/s eta 0:12:06

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting polar
  Downloading polar-0.0.127.tar.gz (11 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: pandas in c:\users\preet kumar\appdata\local\programs\python\python311\lib\site-packages (from polar) (3.0.5)
Requirement already satisfied: numpy in c:\users\preet kumar\appdata\local\programs\python\python311\lib\site-packages (from polar) (2.4.6)
Collecting scipy (from polar)
  Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------------------- ------------------ 30.7/61.0 kB 660.6 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/61.0 kB 660.6 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/61.0 kB 660.6 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/61.0 kB 660.6 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.0 kB 201.8 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 216.7 kB/s eta 0:00:00
Collecting statsmodels (from polar)
  Downloading statsmodels-0.15.0-cp311-cp311-win_amd64.whl.metadata (9.6 kB)
Collecting scikit-learn (from polar)
  Downloading scikit_learn-1.9.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting seaborn (from polar)
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting cryptography (from polar)
  Downloading cryptography-50.0.1-cp311-abi3-win_amd64.whl.metadata (4.3 kB)
Collecting nltk (from polar)
  Downloading nltk-3.10.3-py3-none-any.whl.metadata (3.2 kB)
Collecting python-pptx (from polar)
  Downloading python_pptx-1.0.2-py3-none-any.whl.metadata (2.5 kB)
Collecting imblearn (from polar)
  Downloading imblearn-0.0-py2.py3-none-any.whl.metadata (355 bytes)
Requirement already satisfied: cffi>=2.0.0 in c:\users\preet kumar\appdata\local\programs\python\python311\lib\site-packages (from cryptography->polar) (2.1.1)
Collecting imbalanced-learn (from imblearn->polar)
  Downloading imbalanced_learn-0.14.2-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: defusedxml in c:\users\preet kumar\appdata\local\programs\python\python311\lib\site-packages (from nltk->polar) (0.7.1)
Requirement already satisfied: click in c:\users\preet kumar\appdata\local\programs\python\python311\lib\site-packages (from nltk->polar) (8.4.2)
Collecting joblib (from nltk->polar)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting regex>=2021.8.3 (from nltk->polar)
  Downloading regex-2026.7.19-cp311-cp311-win_amd64.whl.metadata (41 kB)
     ---------------------------------------- 0.0/41.6 kB ? eta -:--:--
     ---------------------------- --------- 30.7/41.6 kB 640.0 kB/s eta 0:00:01
     -------------------------------------- 41.6/41.6 kB 497.3 kB/s eta 0:00:00
Requirement already satisfied: tqdm in c:\users\preet kumar\appdata\local\programs\python\python311\lib\site-packages (from nltk->polar) (4.70.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\preet kumar\appdata\local\programs\python\python311\lib\site-packages (from pandas->polar) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\preet kumar\appdata\local\programs\python\python311\lib\site-packages (from pandas->polar) (2026.3)
Collecting Pillow>=3.3.2 (from python-pptx->polar)
  Downloading pillow-12.3.0-cp311-cp311-win_amd64.whl.metadata (9.3 kB)
Collecting XlsxWriter>=0.5.7 (from python-pptx->polar)
  Downloading xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
Collecting lxml>=3.1.0 (from python-pptx->polar)
  Downloading lxml-6.1.2-cp311-cp311-win_amd64.whl.metadata (3.4 kB)
Requirement already satisfied: typing-extensions>=4.9.0 in c:\users\preet kumar\appdata\local\programs\python\python311\lib\site-packages (from python-pptx->polar) (4.16.0)
Collecting narwhals>=2.0.1 (from scikit-learn->polar)
  Downloading narwhals-2.25.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn->polar)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting matplotlib!=3.6.1,>=3.4 (from seaborn->polar)
  Downloading matplotlib-3.11.1-cp311-cp311-win_amd64.whl.metadata (80 kB)
     ---------------------------------------- 0.0/80.3 kB ? eta -:--:--
     ----------------------------------- ---- 71.7/80.3 kB ? eta -:--:--
     ---------------------------------------- 80.3/80.3 kB 2.2 MB/s eta 0:00:00
Collecting patsy>=0.5.6 (from statsmodels->polar)
  Downloading patsy-1.0.3-py2.py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: packaging>=21.3 in c:\users\preet kumar\appdata\local\programs\python\python311\lib\site-packages (from statsmodels->polar) (26.3)
Collecting formulaic>=1.1.0 (from statsmodels->polar)
  Downloading formulaic-1.2.2-py3-none-any.whl.metadata (7.0 kB)
Requirement already satisfied: pycparser in c:\users\preet kumar\appdata\local\programs\python\python311\lib\site-packages (from cffi>=2.0.0->cryptography->polar) (3.0)
Collecting interface-meta>=1.2.0 (from formulaic>=1.1.0->statsmodels->polar)
  Downloading interface_meta-2.0.1-py3-none-any.whl.metadata (6.4 kB)
Collecting wrapt>=1.0 (from formulaic>=1.1.0->statsmodels->polar)
  Downloading wrapt-2.4.0-cp311-cp311-win_amd64.whl.metadata (7.6 kB)
Collecting contourpy>=1.0.1 (from matplotlib!=3.6.1,>=3.4->seaborn->polar)
  Downloading contourpy-1.3.3-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib!=3.6.1,>=3.4->seaborn->polar)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib!=3.6.1,>=3.4->seaborn->polar)
  Downloading fonttools-4.63.0-cp311-cp311-win_amd64.whl.metadata (121 kB)
     ---------------------------------------- 0.0/121.0 kB ? eta -:--:--
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     -------------------------- ------------ 81.9/121.0 kB 4.8 MB/s eta 0:00:01
     ---------------------------- --------- 92.2/121.0 kB 51.4 kB/s eta 0:00:01
     ---------------------------- --------- 92.2/121.0 kB 51.4 kB/s eta 0:00:01
     ---------------------------- --------- 92.2/121.0 kB 51.4 kB/s eta 0:00:01
     ---------------------------- --------- 92.2/121.0 kB 51.4 kB/s eta 0:00:01
     ---------------------------------- -- 112.6/121.0 kB 58.0 kB/s eta 0:00:01
     ------------------------------------- 121.0/121.0 kB 61.7 kB/s eta 0:00:00
Collecting kiwisolver>=1.3.1 (from matplotlib!=3.6.1,>=3.4->seaborn->polar)
  Downloading kiwisolver-1.5.1-cp311-cp311-win_amd64.whl.metadata (5.2 kB)
Collecting pyparsing>=3 (from matplotlib!=3.6.1,>=3.4->seaborn->polar)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in c:\users\preet kumar\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas->polar) (1.17.0)
Requirement already satisfied: colorama in c:\users\preet kumar\appdata\local\programs\python\python311\lib\site-packages (from click->nltk->polar) (0.4.6)
Collecting sklearn-compat<0.2,>=0.1.6 (from imbalanced-learn->imblearn->polar)
  Downloading sklearn_compat-0.1.6-py3-none-any.whl.metadata (22 kB)
Downloading cryptography-50.0.1-cp311-abi3-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.8 MB 1.4 MB/s eta 0:00:03
   ---------------------------------------- 0.0/3.8 MB 495.5 kB/s eta 0:00:08
    --------------------------------------- 0.1/3.8 MB 563.7 kB/s eta 0:00:07
    --------------------------------------- 0.1/3.8 MB 585.1 kB/s eta 0:00:07
   - -------------------------------------- 0.1/3.8 MB 711.9 kB/s eta 0:00:06
   - -------------------------------------- 0.2/3.8 MB 743.9 kB/s eta 0:00:05
   -- ------------------------------------- 0.2/3.8 MB 765.3 kB/s eta 0:00:05
   -- ------------------------------------- 0.2/3.8 MB 765.3 kB/s eta 0:00:05
   -- ------------------------------------- 0.3/3.8 MB 713.1 kB/s eta 0:00:06
   -- ------------------------------------- 0.3/3.8 MB 681.0 kB/s eta 0:00:06
   --- ------------------------------------ 0.3/3.8 MB 703.7 kB/s eta 0:00:06
   --- ------------------------------------ 0.4/3.8 MB 740.5 kB/s eta 0:00:05
   ---- ----------------------------------- 0.4/3.8 MB 790.7 kB/s eta 0:00:05
   ---- ----------------------------------- 0.4/3.8 MB 790.7 kB/s eta 0:00:05
   ---- ----------------------------------- 0.5/3.8 MB 723.0 kB/s eta 0:00:05
   ----- ---------------------------------- 0.5/3.8 MB 764.9 kB/s eta 0:00:05
   ----- ---------------------------------- 0.6/3.8 MB 786.6 kB/s eta 0:00:05
   ------ --------------------------------- 0.6/3.8 MB 778.2 kB/s eta 0:00:05
   ------ --------------------------------- 0.6/3.8 MB 778.2 kB/s eta 0:00:05
   ------ --------------------------------- 0.6/3.8 MB 769.3 kB/s eta 0:00:05
   ------- -------------------------------- 0.7/3.8 MB 798.7 kB/s eta 0:00:04
   ------- -------------------------------- 0.7/3.8 MB 799.7 kB/s eta 0:00:04
   -------- ------------------------------- 0.8/3.8 MB 780.5 kB/s eta 0:00:04
   -------- ------------------------------- 0.8/3.8 MB 780.5 kB/s eta 0:00:04
   -------- ------------------------------- 0.8/3.8 MB 753.1 kB/s eta 0:00:05
   -------- ------------------------------- 0.8/3.8 MB 738.7 kB/s eta 0:00:05
   -------- ------------------------------- 0.8/3.8 MB 747.9 kB/s eta 0:00:05
   --------- ------------------------------ 0.9/3.8 MB 751.4 kB/s eta 0:00:04
   --------- ------------------------------ 0.9/3.8 MB 759.2 kB/s eta 0:00:04
   --------- ------------------------------ 0.9/3.8 MB 759.2 kB/s eta 0:00:04
   ---------- ----------------------------- 1.0/3.8 MB 765.8 kB/s eta 0:00:04
   ---------- ----------------------------- 1.0/3.8 MB 765.8 kB/s eta 0:00:04
   ---------- ----------------------------- 1.0/3.8 MB 765.8 kB/s eta 0:00:04
   ---------- ----------------------------- 1.0/3.8 MB 765.8 kB/s eta 0:00:04
   ---------- ----------------------------- 1.0/3.8 MB 765.8 kB/s eta 0:00:04
   ----------- ---------------------------- 1.1/3.8 MB 710.0 kB/s eta 0:00:04
   ----------- ---------------------------- 1.1/3.8 MB 708.3 kB/s eta 0:00:04
   ----------- ---------------------------- 1.1/3.8 MB 708.3 kB/s eta 0:00:04
   ----------- ---------------------------- 1.1/3.8 MB 708.3 kB/s eta 0:00:04
   ----------- ---------------------------- 1.1/3.8 MB 673.7 kB/s eta 0:00:05
   ------------ --------------------------- 1.2/3.8 MB 679.8 kB/s eta 0:00:04
   ------------ --------------------------- 1.2/3.8 MB 679.1 kB/s eta 0:00:04
   ------------ --------------------------- 1.2/3.8 MB 684.6 kB/s eta 0:00:04
   ------------ --------------------------- 1.2/3.8 MB 678.1 kB/s eta 0:00:04
   ------------- -------------------------- 1.3/3.8 MB 677.5 kB/s eta 0:00:04
   ------------- -------------------------- 1.3/3.8 MB 682.7 kB/s eta 0:00:04
   ------------- -------------------------- 1.3/3.8 MB 687.2 kB/s eta 0:00:04
   -------------- ------------------------- 1.4/3.8 MB 686.5 kB/s eta 0:00:04
   -------------- ------------------------- 1.4/3.8 MB 685.7 kB/s eta 0:00:04
   -------------- ------------------------- 1.4/3.8 MB 685.7 kB/s eta 0:00:04
   --------------- ------------------------ 1.5/3.8 MB 699.2 kB/s eta 0:00:04
   --------------- ------------------------ 1.5/3.8 MB 703.4 kB/s eta 0:00:04
   --------------- ------------------------ 1.5/3.8 MB 703.4 kB/s eta 0:00:04
   --------------- ------------------------ 1.5/3.8 MB 687.6 kB/s eta 0:00:04
   ---------------- ----------------------- 1.6/3.8 MB 700.8 kB/s eta 0:00:04
   ----------------- ---------------------- 1.6/3.8 MB 708.6 kB/s eta 0:00:04
   ----------------- ---------------------- 1.6/3.8 MB 708.6 kB/s eta 0:00:04
   ----------------- ---------------------- 1.7/3.8 MB 694.1 kB/s eta 0:00:04
   ----------------- ---------------------- 1.7/3.8 MB 684.6 kB/s eta 0:00:04
   ------------------ --------------------- 1.8/3.8 MB 708.6 kB/s eta 0:00:03
   ------------------ --------------------- 1.8/3.8 MB 712.7 kB/s eta 0:00:03
   ------------------ --------------------- 1.8/3.8 MB 712.7 kB/s eta 0:00:03
   ------------------- -------------------- 1.8/3.8 MB 698.6 kB/s eta 0:00:03
   ------------------- -------------------- 1.9/3.8 MB 705.9 kB/s eta 0:00:03
   ------------------- -------------------- 1.9/3.8 MB 704.6 kB/s eta 0:00:03
   -------------------- ------------------- 2.0/3.8 MB 707.5 kB/s eta 0:00:03
   -------------------- ------------------- 2.0/3.8 MB 714.3 kB/s eta 0:00:03
   -------------------- ------------------- 2.0/3.8 MB 714.3 kB/s eta 0:00:03
   -------------------- ------------------- 2.0/3.8 MB 714.3 kB/s eta 0:00:03
   --------------------- ------------------ 2.1/3.8 MB 719.3 kB/s eta 0:00:03
   --------------------- ------------------ 2.1/3.8 MB 722.4 kB/s eta 0:00:03
   ---------------------- ----------------- 2.1/3.8 MB 714.3 kB/s eta 0:00:03
   ---------------------- ----------------- 2.1/3.8 MB 706.4 kB/s eta 0:00:03
   ---------------------- ----------------- 2.2/3.8 MB 712.3 kB/s eta 0:00:03
   ----------------------- ---------------- 2.2/3.8 MB 714.9 kB/s eta 0:00:03
   ----------------------- ---------------- 2.2/3.8 MB 714.9 kB/s eta 0:00:03
   ----------------------- ---------------- 2.3/3.8 MB 717.1 kB/s eta 0:00:03
   ------------------------ --------------- 2.3/3.8 MB 718.9 kB/s eta 0:00:03
   ------------------------ --------------- 2.3/3.8 MB 718.9 kB/s eta 0:00:03
   ------------------------ --------------- 2.4/3.8 MB 717.8 kB/s eta 0:00:03
   ------------------------- -------------- 2.4/3.8 MB 716.6 kB/s eta 0:00:03
   ------------------------- -------------- 2.4/3.8 MB 716.4 kB/s eta 0:00:02
   ------------------------- -------------- 2.4/3.8 MB 712.5 kB/s eta 0:00:02
   ------------------------- -------------- 2.5/3.8 MB 714.3 kB/s eta 0:00:02
   -------------------------- ------------- 2.5/3.8 MB 714.2 kB/s eta 0:00:02
   -------------------------- ------------- 2.5/3.8 MB 713.7 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/3.8 MB 715.5 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/3.8 MB 712.2 kB/s eta 0:00:02
   --------------------------- ------------ 2.6/3.8 MB 720.2 kB/s eta 0:00:02
   --------------------------- ------------ 2.7/3.8 MB 719.0 kB/s eta 0:00:02
   ---------------------------- ----------- 2.7/3.8 MB 724.0 kB/s eta 0:00:02
   ---------------------------- ----------- 2.7/3.8 MB 724.0 kB/s eta 0:00:02
   ---------------------------- ----------- 2.8/3.8 MB 716.9 kB/s eta 0:00:02
   ----------------------------- ---------- 2.8/3.8 MB 721.8 kB/s eta 0:00:02
   ----------------------------- ---------- 2.9/3.8 MB 725.8 kB/s eta 0:00:02
   ------------------------------ --------- 2.9/3.8 MB 727.9 kB/s eta 0:00:02
   ------------------------------ --------- 2.9/3.8 MB 727.0 kB/s eta 0:00:02
   ------------------------------ --------- 3.0/3.8 MB 731.6 kB/s eta 0:00:02
   ------------------------------- -------- 3.0/3.8 MB 733.2 kB/s eta 0:00:02
   ------------------------------- -------- 3.0/3.8 MB 734.8 kB/s eta 0:00:02
   -------------------------------- ------- 3.1/3.8 MB 736.3 kB/s eta 0:00:02
   -------------------------------- ------- 3.1/3.8 MB 738.6 kB/s eta 0:00:02
   -------------------------------- ------- 3.2/3.8 MB 739.7 kB/s eta 0:00:01
   --------------------------------- ------ 3.2/3.8 MB 743.3 kB/s eta 0:00:01
   ---------------------------------- ----- 3.3/3.8 MB 749.6 kB/s eta 0:00:01
   ---------------------------------- ----- 3.3/3.8 MB 749.0 kB/s eta 0:00:01
   ---------------------------------- ----- 3.3/3.8 MB 752.4 kB/s eta 0:00:01
   ----------------------------------- ---- 3.4/3.8 MB 753.9 kB/s eta 0:00:01
   ----------------------------------- ---- 3.4/3.8 MB 755.5 kB/s eta 0:00:01
   ----------------------------------- ---- 3.5/3.8 MB 756.7 kB/s eta 0:00:01
   ------------------------------------ --- 3.5/3.8 MB 759.8 kB/s eta 0:00:01
   ------------------------------------ --- 3.5/3.8 MB 761.4 kB/s eta 0:00:01
   ------------------------------------- -- 3.6/3.8 MB 762.7 kB/s eta 0:00:01
   ------------------------------------- -- 3.6/3.8 MB 763.6 kB/s eta 0:00:01
   -------------------------------------- - 3.7/3.8 MB 767.5 kB/s eta 0:00:01
   -------------------------------------- - 3.7/3.8 MB 770.3 kB/s eta 0:00:01
   -------------------------------------- - 3.7/3.8 MB 767.1 kB/s eta 0:00:01
   ---------------------------------------  3.8/3.8 MB 772.3 kB/s eta 0:00:01
   ---------------------------------------  3.8/3.8 MB 769.1 kB/s eta 0:00:01
   ---------------------------------------  3.8/3.8 MB 768.4 kB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 764.2 kB/s eta 0:00:00
Downloading imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Downloading nltk-3.10.3-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   - -------------------------------------- 0.1/1.8 MB 1.9 MB/s eta 0:00:01

In [73]:
import polars as pl
print(pl.__version__)

1.44.1

In [78]:
%pip install fastexcel

Collecting fastexcel
  Downloading fastexcel-0.21.0-cp310-abi3-win_amd64.whl.metadata (7.4 kB)
Downloading fastexcel-0.21.0-cp310-abi3-win_amd64.whl (3.3 MB)
   ---------------------------------------- 0.0/3.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/3.3 MB ? eta -:--:--
    --------------------------------------- 0.1/3.3 MB 1.1 MB/s eta 0:00:03
    --------------------------------------- 0.1/3.3 MB 563.7 kB/s eta 0:00:06
   - -------------------------------------- 0.1/3.3 MB 585.1 kB/s eta 0:00:06
   - -------------------------------------- 0.1/3.3 MB 585.1 kB/s eta 0:00:06
   - -------------------------------------- 0.1/3.3 MB 409.6 kB/s eta 0:00:08
   - -------------------------------------- 0.1/3.3 MB 380.5 kB/s eta 0:00:09
   - -------------------------------------- 0.1/3.3 MB 370.8 kB/s eta 0:00:09
   - -------------------------------------- 0.1/3.3 MB 370.8 kB/s eta 0:00:09
   - -------------------------------------- 0.2/3.3 MB 340.5 kB/s eta 0:00:10
   -- ------------------------------------- 0.2/3.3 MB 357.9 kB/s eta 0:00:09
   -- ------------------------------------- 0.2/3.3 MB 357.9 kB/s eta 0:00:09
   -- ------------------------------------- 0.2/3.3 MB 336.6 kB/s eta 0:00:10
   -- ------------------------------------- 0.2/3.3 MB 344.1 kB/s eta 0:00:09
   -- ------------------------------------- 0.2/3.3 MB 327.9 kB/s eta 0:00:10
   --- ------------------------------------ 0.3/3.3 MB 334.8 kB/s eta 0:00:10
   --- ------------------------------------ 0.3/3.3 MB 340.9 kB/s eta 0:00:09
   --- ------------------------------------ 0.3/3.3 MB 328.0 kB/s eta 0:00:10
   --- ------------------------------------ 0.3/3.3 MB 339.1 kB/s eta 0:00:09
   --- ------------------------------------ 0.3/3.3 MB 339.1 kB/s eta 0:00:09
   ---- ----------------------------------- 0.3/3.3 MB 333.0 kB/s eta 0:00:09
   ---- ----------------------------------- 0.4/3.3 MB 337.7 kB/s eta 0:00:09
   ---- ----------------------------------- 0.4/3.3 MB 332.5 kB/s eta 0:00:09
   ---- ----------------------------------- 0.4/3.3 MB 336.8 kB/s eta 0:00:09
   ---- ----------------------------------- 0.4/3.3 MB 332.3 kB/s eta 0:00:09
   ----- ---------------------------------- 0.4/3.3 MB 336.3 kB/s eta 0:00:09
   ----- ---------------------------------- 0.4/3.3 MB 344.1 kB/s eta 0:00:09
   ----- ---------------------------------- 0.5/3.3 MB 335.6 kB/s eta 0:00:09
   ----- ---------------------------------- 0.5/3.3 MB 342.6 kB/s eta 0:00:09
   ------ --------------------------------- 0.5/3.3 MB 342.0 kB/s eta 0:00:09
   ------ --------------------------------- 0.5/3.3 MB 348.8 kB/s eta 0:00:09
   ------ --------------------------------- 0.5/3.3 MB 344.7 kB/s eta 0:00:09
   ------ --------------------------------- 0.6/3.3 MB 347.5 kB/s eta 0:00:08
   ------ --------------------------------- 0.6/3.3 MB 340.3 kB/s eta 0:00:09
   ------- -------------------------------- 0.6/3.3 MB 343.2 kB/s eta 0:00:08
   ------- -------------------------------- 0.6/3.3 MB 348.7 kB/s eta 0:00:08
   ------- -------------------------------- 0.6/3.3 MB 345.2 kB/s eta 0:00:08
   ------- -------------------------------- 0.6/3.3 MB 350.7 kB/s eta 0:00:08
   ------- -------------------------------- 0.6/3.3 MB 347.3 kB/s eta 0:00:08
   -------- ------------------------------- 0.7/3.3 MB 349.5 kB/s eta 0:00:08
   -------- ------------------------------- 0.7/3.3 MB 351.3 kB/s eta 0:00:08
   -------- ------------------------------- 0.7/3.3 MB 353.3 kB/s eta 0:00:08
   -------- ------------------------------- 0.7/3.3 MB 353.3 kB/s eta 0:00:08
   -------- ------------------------------- 0.7/3.3 MB 342.5 kB/s eta 0:00:08
   --------- ------------------------------ 0.7/3.3 MB 342.0 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.3 MB 346.5 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.3 MB 339.1 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.3 MB 339.1 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.3 MB 339.1 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.3 MB 339.1 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.3 MB 327.7 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.3 MB 327.7 kB/s eta 0:00:08
   --------- ------------------------------ 0.8/3.3 MB 327.7 kB/s eta 0:00:08
   ---------- ----------------------------- 0.8/3.3 MB 327.7 kB/s eta 0:00:08
   ---------- ----------------------------- 0.9/3.3 MB 331.6 kB/s eta 0:00:08
   ---------- ----------------------------- 0.9/3.3 MB 327.7 kB/s eta 0:00:08
   ---------- ----------------------------- 0.9/3.3 MB 329.6 kB/s eta 0:00:08
   ----------- ---------------------------- 0.9/3.3 MB 333.3 kB/s eta 0:00:08
   ----------- ---------------------------- 0.9/3.3 MB 333.3 kB/s eta 0:00:08
   ----------- ---------------------------- 1.0/3.3 MB 335.0 kB/s eta 0:00:08
   ----------- ---------------------------- 1.0/3.3 MB 334.7 kB/s eta 0:00:07
   ------------ --------------------------- 1.0/3.3 MB 338.1 kB/s eta 0:00:07
   ------------ --------------------------- 1.0/3.3 MB 338.1 kB/s eta 0:00:07
   ------------ --------------------------- 1.0/3.3 MB 337.8 kB/s eta 0:00:07
   ------------ --------------------------- 1.1/3.3 MB 337.7 kB/s eta 0:00:07
   ------------ --------------------------- 1.1/3.3 MB 337.4 kB/s eta 0:00:07
   ------------- -------------------------- 1.1/3.3 MB 340.6 kB/s eta 0:00:07
   ------------- -------------------------- 1.1/3.3 MB 340.5 kB/s eta 0:00:07
   ------------- -------------------------- 1.1/3.3 MB 340.5 kB/s eta 0:00:07
   ------------- -------------------------- 1.1/3.3 MB 338.5 kB/s eta 0:00:07
   ------------- -------------------------- 1.2/3.3 MB 341.4 kB/s eta 0:00:07
   -------------- ------------------------- 1.2/3.3 MB 344.4 kB/s eta 0:00:07
   -------------- ------------------------- 1.2/3.3 MB 343.9 kB/s eta 0:00:07
   -------------- ------------------------- 1.2/3.3 MB 343.8 kB/s eta 0:00:07
   -------------- ------------------------- 1.2/3.3 MB 345.0 kB/s eta 0:00:07
   --------------- ------------------------ 1.3/3.3 MB 344.6 kB/s eta 0:00:06
   --------------- ------------------------ 1.3/3.3 MB 346.0 kB/s eta 0:00:06
   --------------- ------------------------ 1.3/3.3 MB 347.2 kB/s eta 0:00:06
   --------------- ------------------------ 1.3/3.3 MB 347.0 kB/s eta 0:00:06
   ---------------- ----------------------- 1.3/3.3 MB 349.2 kB/s eta 0:00:06
   ---------------- ----------------------- 1.4/3.3 MB 349.1 kB/s eta 0:00:06
   ---------------- ----------------------- 1.4/3.3 MB 350.1 kB/s eta 0:00:06
   ---------------- ----------------------- 1.4/3.3 MB 348.5 kB/s eta 0:00:06
   ----------------- ---------------------- 1.4/3.3 MB 352.0 kB/s eta 0:00:06
   ----------------- ---------------------- 1.4/3.3 MB 350.4 kB/s eta 0:00:06
   ----------------- ---------------------- 1.5/3.3 MB 352.8 kB/s eta 0:00:06
   ----------------- ---------------------- 1.5/3.3 MB 352.8 kB/s eta 0:00:06
   ----------------- ---------------------- 1.5/3.3 MB 352.2 kB/s eta 0:00:06
   ------------------ --------------------- 1.5/3.3 MB 353.1 kB/s eta 0:00:06
   ------------------ --------------------- 1.5/3.3 MB 355.2 kB/s eta 0:00:06
   ------------------ --------------------- 1.5/3.3 MB 354.9 kB/s eta 0:00:05
   ------------------ --------------------- 1.6/3.3 MB 355.8 kB/s eta 0:00:05
   ------------------- -------------------- 1.6/3.3 MB 355.4 kB/s eta 0:00:05
   ------------------- -------------------- 1.6/3.3 MB 356.4 kB/s eta 0:00:05
   ------------------- -------------------- 1.6/3.3 MB 357.1 kB/s eta 0:00:05
   ------------------- -------------------- 1.6/3.3 MB 357.1 kB/s eta 0:00:05
   ------------------- -------------------- 1.6/3.3 MB 357.1 kB/s eta 0:00:05
   ------------------- -------------------- 1.6/3.3 MB 357.1 kB/s eta 0:00:05
   ------------------- -------------------- 1.6/3.3 MB 357.1 kB/s eta 0:00:05
   -------------------- ------------------- 1.7/3.3 MB 356.7 kB/s eta 0:00:05
   -------------------- ------------------- 1.7/3.3 MB 356.7 kB/s eta 0:00:05
   -------------------- ------------------- 1.7/3.3 MB 355.2 kB/s eta 0:00:05
   --------------------- ------------------ 1.8/3.3 MB 356.0 kB/s eta 0:00:05
   --------------------- ------------------ 1.8/3.3 MB 355.8 kB/s eta 0:00:05
   --------------------- ------------------ 1.8/3.3 MB 355.4 kB/s eta 0:00:05
   --------------------- ------------------ 1.8/3.3 MB 354.2 kB/s eta 0:00:05
   --------------------- ------------------ 1.8/3.3 MB 354.9 kB/s eta 0:00:05
   --------------------- ------------------ 1.8/3.3 MB 354.9 kB/s eta 0:00:05
   ---------------------- ----------------- 1.8/3.3 MB 353.4 kB/s eta 0:00:05
   ---------------------- ----------------- 1.8/3.3 MB 353.4 kB/s eta 0:00:05
   ---------------------- ----------------- 1.9/3.3 MB 353.0 kB/s eta 0:00:05
   ---------------------- ----------------- 1.9/3.3 MB 352.6 kB/s eta 0:00:05
   ----------------------- ---------------- 1.9/3.3 MB 353.4 kB/s eta 0:00:04
   ----------------------- ---------------- 1.9/3.3 MB 352.2 kB/s eta 0:00:04
   ----------------------- ---------------- 1.9/3.3 MB 353.9 kB/s eta 0:00:04
   ----------------------- ---------------- 2.0/3.3 MB 352.8 kB/s eta 0:00:04
   ----------------------- ---------------- 2.0/3.3 MB 352.5 kB/s eta 0:00:04
   ------------------------ --------------- 2.0/3.3 MB 354.2 kB/s eta 0:00:04
   ------------------------ --------------- 2.0/3.3 MB 354.0 kB/s eta 0:00:04
   ------------------------ --------------- 2.0/3.3 MB 354.6 kB/s eta 0:00:04
   ------------------------ --------------- 2.0/3.3 MB 354.6 kB/s eta 0:00:04
   ------------------------- -------------- 2.1/3.3 MB 355.9 kB/s eta 0:00:04
   ------------------------- -------------- 2.1/3.3 MB 355.8 kB/s eta 0:00:04
   ------------------------- -------------- 2.1/3.3 MB 355.4 kB/s eta 0:00:04
   ------------------------- -------------- 2.1/3.3 MB 353.5 kB/s eta 0:00:04
   ------------------------- -------------- 2.1/3.3 MB 355.0 kB/s eta 0:00:04
   -------------------------- ------------- 2.2/3.3 MB 355.7 kB/s eta 0:00:04
   -------------------------- ------------- 2.2/3.3 MB 357.0 kB/s eta 0:00:04
   -------------------------- ------------- 2.2/3.3 MB 356.9 kB/s eta 0:00:04
   -------------------------- ------------- 2.2/3.3 MB 357.5 kB/s eta 0:00:04
   --------------------------- ------------ 2.2/3.3 MB 359.0 kB/s eta 0:00:03
   --------------------------- ------------ 2.3/3.3 MB 359.4 kB/s eta 0:00:03
   --------------------------- ------------ 2.3/3.3 MB 358.4 kB/s eta 0:00:03
   --------------------------- ------------ 2.3/3.3 MB 359.8 kB/s eta 0:00:03
   ---------------------------- ----------- 2.3/3.3 MB 361.1 kB/s eta 0:00:03
   ---------------------------- ----------- 2.4/3.3 MB 361.7 kB/s eta 0:00:03
   ---------------------------- ----------- 2.4/3.3 MB 360.6 kB/s eta 0:00:03
   ---------------------------- ----------- 2.4/3.3 MB 362.0 kB/s eta 0:00:03
   ----------------------------- ---------- 2.4/3.3 MB 363.4 kB/s eta 0:00:03
   ----------------------------- ---------- 2.4/3.3 MB 363.2 kB/s eta 0:00:03
   ----------------------------- ---------- 2.4/3.3 MB 363.6 kB/s eta 0:00:03
   ----------------------------- ---------- 2.5/3.3 MB 365.0 kB/s eta 0:00:03
   ----------------------------- ---------- 2.5/3.3 MB 365.4 kB/s eta 0:00:03
   ------------------------------ --------- 2.5/3.3 MB 366.6 kB/s eta 0:00:03
   ------------------------------ --------- 2.5/3.3 MB 366.4 kB/s eta 0:00:03
   ------------------------------ --------- 2.5/3.3 MB 366.9 kB/s eta 0:00:03
   ------------------------------- -------- 2.6/3.3 MB 368.0 kB/s eta 0:00:03
   ------------------------------- -------- 2.6/3.3 MB 368.5 kB/s eta 0:00:02
   ------------------------------- -------- 2.6/3.3 MB 368.3 kB/s eta 0:00:02
   ------------------------------- -------- 2.6/3.3 MB 369.6 kB/s eta 0:00:02
   ------------------------------- -------- 2.7/3.3 MB 370.0 kB/s eta 0:00:02
   -------------------------------- ------- 2.7/3.3 MB 369.8 kB/s eta 0:00:02
   -------------------------------- ------- 2.7/3.3 MB 370.1 kB/s eta 0:00:02
   -------------------------------- ------- 2.7/3.3 MB 371.3 kB/s eta 0:00:02
   --------------------------------- ------ 2.7/3.3 MB 371.5 kB/s eta 0:00:02
   --------------------------------- ------ 2.8/3.3 MB 372.7 kB/s eta 0:00:02
   --------------------------------- ------ 2.8/3.3 MB 371.8 kB/s eta 0:00:02
   --------------------------------- ------ 2.8/3.3 MB 374.1 kB/s eta 0:00:02
   ---------------------------------- ----- 2.8/3.3 MB 373.2 kB/s eta 0:00:02
   ---------------------------------- ----- 2.8/3.3 MB 374.3 kB/s eta 0:00:02
   ---------------------------------- ----- 2.9/3.3 MB 374.1 kB/s eta 0:00:02
   ---------------------------------- ----- 2.9/3.3 MB 375.7 kB/s eta 0:00:02
   ----------------------------------- ---- 2.9/3.3 MB 374.7 kB/s eta 0:00:02
   ----------------------------------- ---- 2.9/3.3 MB 375.8 kB/s eta 0:00:02
   ----------------------------------- ---- 2.9/3.3 MB 374.1 kB/s eta 0:00:02
   ----------------------------------- ---- 3.0/3.3 MB 376.4 kB/s eta 0:00:01
   ------------------------------------ --- 3.0/3.3 MB 375.4 kB/s eta 0:00:01
   ------------------------------------ --- 3.0/3.3 MB 376.5 kB/s eta 0:00:01
   ------------------------------------ --- 3.0/3.3 MB 376.3 kB/s eta 0:00:01
   ------------------------------------ --- 3.1/3.3 MB 377.8 kB/s eta 0:00:01
   ------------------------------------- -- 3.1/3.3 MB 376.8 kB/s eta 0:00:01
   ------------------------------------- -- 3.1/3.3 MB 377.9 kB/s eta 0:00:01
   ------------------------------------- -- 3.1/3.3 MB 377.7 kB/s eta 0:00:01
   ------------------------------------- -- 3.1/3.3 MB 379.1 kB/s eta 0:00:01
   -------------------------------------- - 3.2/3.3 MB 378.9 kB/s eta 0:00:01
   -------------------------------------- - 3.2/3.3 MB 378.4 kB/s eta 0:00:01
   -------------------------------------- - 3.2/3.3 MB 380.1 kB/s eta 0:00:01
   -------------------------------------- - 3.2/3.3 MB 379.9 kB/s eta 0:00:01
   ---------------------------------------  3.3/3.3 MB 381.2 kB/s eta 0:00:01
   ---------------------------------------  3.3/3.3 MB 381.0 kB/s eta 0:00:01
   ---------------------------------------  3.3/3.3 MB 382.0 kB/s eta 0:00:01
   ---------------------------------------- 3.3/3.3 MB 382.2 kB/s eta 0:00:00
Installing collected packages: fastexcel
Successfully installed fastexcel-0.21.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [82]:
pldf = pl.read_excel('data/result.xlsx')

Could not determine dtype for column 26, falling back to string
Could not determine dtype for column 27, falling back to string
Could not determine dtype for column 28, falling back to string
Could not determine dtype for column 29, falling back to string
Could not determine dtype for column 30, falling back to string
Could not determine dtype for column 31, falling back to string
Could not determine dtype for column 32, falling back to string
C:\Users\Preet Kumar\AppData\Local\Temp\ipykernel_18616\3276904736.py:1: FutureWarning: from_arrow(<ArrowStreamExportable>) will return a Series instead of a DataFrame in 2.0. To avoid this warning, pass the ArrowStreamExportable to either `pl.DataFrame` or `pl.Series` instead based on your desired output type.
  pldf = pl.read_excel('data/result.xlsx')

In [81]:
pdf = pd.read_excel('data/result.xlsx')

# Reading Text Files

In [86]:
pd.read_csv('data/Employees.txt', sep='\t')

    ID     Name  Age       City  Department  Salary
0  101      Ali   25    Karachi          IT   75000
1  102     Sara   28     Lahore          HR   65000
2  103    Ahmed   32  Islamabad          IT   95000
3  104   Fatima   24    Karachi     Finance   70000
4  105   Hassan   35     Lahore          IT  110000
5  106   Ayesha   29  Islamabad          HR   80000
6  107    Usman   31    Karachi     Finance   90000
7  108   Zainab   27     Lahore          IT   85000
8  109    Bilal   40  Islamabad  Management  150000
9  110  Mahnoor   26    Karachi          HR   72000

# Reading Text from JSON/SQL

1. JavaScript on Notation
2. Structured Query Language

In [87]:
import pandas as pd

pd.read_json('data/all_graana_property_links.json')

,url,purpose,property_type,city
0,https://www.graana.com/property/5-marla-house-...,sale,residential,islamabad
1,https://www.graana.com/property/4-marla-house-...,sale,residential,islamabad
2,https://www.graana.com/property/827-sqft-flat-...,sale,residential,islamabad
3,https://www.graana.com/property/1800-sqft-flat...,sale,residential,islamabad
4,https://www.graana.com/property/1-kanal-house-...,sale,residential,islamabad
...,...,...,...,...
392,https://www.graana.com/property/120-sqft-offic...,rent,commercial,karachi
393,https://www.graana.com/property/5-marla-shop-r...,rent,commercial,karachi
394,https://www.graana.com/property/4-marla-shop-r...,rent,commercial,karachi
395,https://www.graana.com/property/4500-sqft-offi...,rent,commercial,karachi
396,https://www.graana.com/property/3-kanal-farmho...,rent,plot,karachi

In [88]:
# Reading Data from URL --> JSON

pd.read_json('https://raw.githubusercontent.com/cs109/2014_data/master/countries.json')

FileNotFoundError: File https://raw.githubusercontent.com/cs109/2014_data/master/countries.json does not exist

# Working with SQL